### ISSUE TITLE
Live images fail to boot due to sysroot.mount race

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#1015]
Fails in openQA, reproducible locally as well. It fails approx. every 4th try.

https://openqa.opensuse.org/tests/881471

The error is
```
[    6.445371] overlayfs: failed to resolve '/run/overlayfs/rw': -2
```

AFAICT this is because `sysroot.mount` does not wait for udev to settle.

**Comment by schaefi** [comment]
I was investigating this one but could not reproduce the error. Could you give me a few more details on the image setup:

* is the iso setup to use a persistent write space ?
* if yes which type of persistency: write into partition on target or write into cow file
* can you reproduce the issue if persistent writing is deactivated.

I also google a bit if other people see similar problem and to my understanding this could
also be an issue in the kernel.

> AFAICT this is because sysroot.mount does not wait for udev to settle.

I checked the code with regards to this and could currently not see where this should happen.
If you take a look at the generator ```dracut/modules.d/90kiwi-live/kiwi-generator.sh``` the sysroot.mount unit is a mount unit that performs the overlay mount. systemd takes over control of a device LiveOS_rootfs for which we also create a timeout unit ```$_dev.device.d```.

I guess when you see the error it happens if systemd issues the mount call and it failed with the given options. That would mean ```/run/overlayfs/rw``` is not "ready" at the time of the call. But this target is only in case of a persistent write space connected to a device node. The code which created that directory would however fail before the actual mount if there would have been a problem. That's why I wonder and asked for more details on the setup of the image

It would be also very helpful if the image could be booted with ```rd.debug rd.kiwi.debug``` and the full serial log could be captured. In the openqa link above I only see the one line you also pasted here.

As I can't reproduce the problem it's hard for me to get an error log

Thanks

**Comment by Vogtinator** [comment]
openQA tests it without any drive other than the DVD, so there is no persistence at all.

> I guess when you see the error it happens if systemd issues the mount call and it failed with the given options. That would mean /run/overlayfs/rw is not "ready" at the time of the call. But this target is only connected to a device in case of a persistent write space. The code which created that directory would however fail before the actual mount if there would have been a problem. That's why I wonder and asked for more details on the setup of the image

The folder just does not exist at that time yet. It's created by https://github.com/SUSE/kiwi/blob/5c02bafa92d8573f83f71bdb83d02dafb5cbc442/dracut/modules.d/90kiwi-live/kiwi-live-lib.sh#L134, which is invoked by an udev rule AFAICT.

> As I can't reproduce the problem it's hard for me to get an error log

I had to boot the .iso five times as well to get it to fail for the first time. With `rd.kiwi.debug` I can't get it to fail at all unfortunately.

**Comment by schaefi** [comment]
> which is invoked by an udev rule AFAICT

yes the code starts as soon as the iso device appears from the initqueue. I think I have an idea... just a sec

**Comment by Vogtinator** [comment]
It looks like the fix wasn't enough, it still fails occasionally: https://openqa.opensuse.org/tests/920487#downloads

**Comment by davidcassany** [comment]
After some attempts I could also reproduce it. Now trying to further dig it

**Comment by davidcassany** [comment]
This what I got using the image being tested in openQA, however I still haven't found a way to jump into the system after the failure neither to extract some more useful logs. 

```
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Started Forward Password Requests to Plymouth Directory Watch.
[  OK  ] Reached target Local Encrypted Volumes.
         Starting dracut pre-mount hook...
[  OK  ] Reached target Paths.
[  OK  ] Started dracut pre-mount hook.
         Mounting /sysroot...
[    7.703176] overlayfs: failed to resolve '/run/overlayfs/rw': -2
[FAILED] Failed to mount /sysroot.
See 'systemctl status sysroot.mount' for details.
[DEPEND] Dependency failed for Initrd Root File System.
[DEPEND] Dependency failed for Reload Configuration from the Real Root.
[ SKIP ] Ordering cycle found, skipping dracut mount hook
[ SKIP ] Ordering cycle found, skipping dracut pre-pivot and cleanup hook
[ SKIP ] Ordering cycle found, skipping dracut pre-pivot and cleanup hook
[ SKIP ] Ordering cycle found, skipping dracut mount hook
[  OK  ] Reached target Local File Systems.
[  OK  ] Reached target System Initialization.
[  OK  ] Listening on Open-iSCSI iscsiuio Socket.
         Starting iSCSI UserSpace I/O driver...
[  OK  ] Listening on Open-iSCSI iscsid Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Reached target Basic System.
[  OK  ] Reached target Initrd File Systems.
[  OK  ] Reached target Initrd Default Target.
[  OK  ] Started iSCSI UserSpace I/O driver.
         Starting Open-iSCSI...
[  OK  ] Started Open-iSCSI.
[  OK  ] Reached target Remote File Systems (Pre).
[  OK  ] Reached target Remote File Systems.
         Starting dracut pre-pivot and cleanup hook...
[  OK  ] Started dracut pre-pivot and cleanup hook.
```

I could not manage to reproduce it with a JeOS iso up to now. I verified that the dracut module includes the commit 958184e81f591b5654529f976ed8f66ebd9e339b

**Comment by davidcassany** [comment]
I hope I have found the issue. I am pretty sure we are seeing side effects of this commit https://github.com/systemd/systemd/commit/d54bab90e64f70c1ecf9b0683a98adb8485ed09e#diff-a55dd3f995e0ee0a2ba83f24f9492eebR473 where the **before** `local-fs.target` is appended to `mount` unit files as a default dependencies. The only mount points that are not affected by these change are listed in https://github.com/systemd/systemd/blob/6ab668337e28ed8e594b0a9ce0b31f2afe3506d8/src/core/mount.c#L398-L419 where `sysroot` is not included. 

Saw similar issues here systemd/systemd#12231 and the fix is adding a `DefaultDependencies=no` tot he sysroot mountpoint.

I managed to reproduce the issue by creating the offending image locally without using OBS (I could not reproduce it by using a JeOS image. Could it be that the race easily appears on large images running on a VM with limited resources? I have no clue). The race easily appears on few attempts. Without running the splash I could see some more logs and see that on failure there is a `dracut-pre-mount.service: Found ordering cycle on dracut-initqueue.service/start` entry which doesn't appear on non failed boots.

With the commit mentioned above appears an issue with the dependencies, since `dracut-pre-mount.service` requires to run **before** `sysroot.mount` and **after** `local-fs.target`, thus if the above mentioned default dependencies apply this turns to be inconsistent. Looks like this ordering cycle causes `pre-mount-hook.service` to run before `dracut-initqueue.service` is done. I could not really dive into it as any attempt to run with `rd.debug` or `systemd.log_level=debug` turned to hide again the race and just boot fine.

I am preparing a PR for that.

**Comment by Vogtinator** [comment]
It's easily reproducible when booting a RPi Kubic image as well, happens on every boot. After removing `dracut-kiwi-lib` and regenerating the initrd the error is gone. I'll try to reproduce it with the PR applied.

**Comment by Vogtinator** [comment]
Nope, the PR only affects live systems. I'll debug a bit further and create a new issue.

**Comment by davidcassany** [comment]
> It's easily reproducible when booting a RPi Kubic image as well, happens on every boot. After removing `dracut-kiwi-lib` and regenerating the initrd the error is gone. I'll try to reproduce it with the PR applied.

Yes this looks like a different issue since there is no `/run/overlayfs/rw` folder if no overlayfs is in use. Probably it is also related with systemd/systemd#12231 too. If it fails every boot it would be nice to run the image appending `rd.debug rd.kiwi.debug rd.shell console=ttyS0` on the kernel command line and grab the serial console to some file. However I don't know how feasible it is for RPi.
