### ISSUE TITLE
checkmedia tool is available on most (all?) architectures

### ISSUE THREAD

**Issue by ggardet** [SUSE/kiwi#1091]
## Problem description
While trying to build a live CD for aarch64, with `mediacheck="true"` attribute, I get the following message:
```
The attribute 'mediacheck' is only supported for x86 platforms,
thus it can't be set to 'true' for the current aarch64 architecture.
```

due to: https://github.com/SUSE/kiwi/blob/6a3b576e6a6d432520f5863bed1f8d909ccf53ff/kiwi/runtime_checker.py#L582

## Expected behaviour
`checkmedia` tool is available on non-x86 architectures (armv6, armv7, aarch64, ppc64, ppc64le, s390x, risc-v), so there should not be this kind of message.

## Steps to reproduce the behaviour
Build live CD for non-x86, with `mediacheck="true"` attribute

## OS and Software information
+ KIWI version: 9.17.37
+ Operating system: openSUSE Tumbleweed
+ OBS version: openSUSE OBS

**Comment by schaefi** [comment]
I agree and will delete this runtime check. However please note this will not allow you to create live iso images for arm. This is because syslinux is not available on arm and the current code uses isolinux.bin to boot. I have a branch open to experiment with using a grub image with eltorito instead of isolinux to overcome this restriction
