### ISSUE TITLE
Improve documentation regarding supported distributions

### ISSUE THREAD

**Issue by ybaumy** [SUSE/kiwi#1108]
## Problem description

> [ ERROR   ]: 14:20:24 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: Unable to detect release version (use '--releasever' to specify release version)

## Expected behaviour
no error?
## Steps to reproduce the behaviour
> sudo kiwi --debug --color-output  system build --description aws/ --target-dir images/
Config can be found here:
[https://gist.github.com/ybaumy/f557e36b28e74473e16f2ad1dac002dd](config.xml)
## OS and Software information
+ KIWI version: 
> KIWI (next generation) version 9.17.39
+ Operating system: 
SLES15SP0
+ OBS version:

**Comment by schaefi** [comment]
I guess you are using an old dnf version. The dnf team has fixed this type of error. Just take a look at the integration test build from here:

* https://build.opensuse.org/package/live_build_log/Virtualization:Appliances:Images:Testing_x86/test-image-centos:Disk/images/x86_64

It's using dnf-4.0.9.2-1.el7_6 and you need the v4 major version for use with kiwi if the buildhost is SUSE

Hope that helps

**Comment by ybaumy** [comment]
this is so typical suse ... Suse Kiwi documentation says: Centos7 is supported. Ok so I even use SLES as a build host. but then I got an error. Open up issue. Answer: Please use dnf version 4.
(which is not in SLES and there are not even rpm for it in the software.opensuse repos.) Well but the issue is closed is it? So does Suse advice me to better use another distribution for building images for centos or in general when using Suse Kiwi software?

**Comment by schaefi** [comment]
Hi, I'm sorry. My intention was just to help you.

> Suse Kiwi documentation says: Centos7 is supported

yes this is true. I really try hard to make sure it is supported. However there are some conditions around the build process that are also not under my control. In this case there is an initiative on the Fedora/RHEL/CentOS side to replace yum by the new package manager dnf. The team around dnf works really hard and we (from the kiwi side) are in contact with them which lead to the situation that we actually could build using dnf if the host is not centos based. That implied the use of the new dnf version which is version 4.x

I had hoped this information would have helped you to solve the problem ?

> which is not in SLES and there are not even rpm for it in the software.opensuse repos

There is the initiative from @Conan-Kudo in https://build.opensuse.org/package/show/home%3APharaoh_Atem%3ADNF_SUSE/dnf
to build dnf for the suse distribution. You are right though it is not packaged on SLES.

Even though I work for SUSE there is not much I can do to make dnf a package maintained in SLES.
If you look at it from a different angle there is also a political aspect involved here because suse's
package manager is zypper and I had a hard time to convince people on the enterprise side to support dnf in addition.

That's why I unfortunately often only can tell "you need dnf 4" but the way to get that on your host might be more tricky than one might think.

So at the very least we could improve the documentation such the scope of support can be explained more detailed. Would that help you ?

I re-open the issue

**Comment by schaefi** [comment]
If we agree on a doc improvement I'd like to ask which place you referred too ? I guess it was here:

* https://opensource.suse.com/kiwi/building.html?highlight=supported%20distr#supported-distributions

Thanks

**Comment by ybaumy** [comment]
Yes that was the documenation page that I was refering to. You know documenation always lacks information. Like I want to build a centos7 image for AWS. so there is the documenation on EC2 AMI for kiwi. It says you need grub2 xen and other tools. Those are not available in centos. 
So what I want to say is.. that documentation in OSS projects always is lacking feature explanation. You get a short example for one case but that was it. As user you are left with hours and hours trying to figure out if it is even possible to get this with that tool to run. So you end up looking at the source code and figure not all cases are working with the supposedly supported distributions.
So sorry that I am complaining but I would really like to minimize the time I am wasting because of bad, incorrect or just information lacking documentation. 

So because of the dnf version. It would really help to make a note on either which buildhost is prefered in order to build supported distributions. 
And examples like [https://github.com/SUSE/kiwi-descriptions/tree/master/centos/x86_64/centos-07.0-JeOS](url) are helping as far as one and really just one use case..

**Comment by schaefi** [comment]
Yep you are right we suffer from incomplete documentation too. I think the world is not ideal here.
I will definitely revise and update the docs as you mentioned. Thanks

I work in the public cloud development team and we use kiwi to build all images you can see on the AWS marketplace for suse and sles. So kiwi supports the AWS target as you are aiming for. I admit I have not done an ami for CentOS with kiwi.

If you need a starting point for an image in EC2 maybe that link is helpful

* https://build.opensuse.org/package/show/Cloud:Images:Leap_15.0/openSUSE-Leap-15.0-EC2-HVM-Guest

**Comment by Conan-Kudo** [comment]
`dnf` is in PackageHub since SLE 15. SLE 15 SP1 has DNF 4.x, which will let you build RHEL 8 images, even (though that's not tested or supported yet).

**Comment by ybaumy** [comment]
@schaefi Thanks for the link. The problem was not building a SLES15 AMI. that worked with the information in the documentation. But centos was not working like that. I had to remove all XEN packages and the described information about maschine and firmware for ec2.
I still got a HVM centos7 image now in AWS. Will still have to verfify if there are some features missing i would need.

@Conan-Kudo thanks for the information

**Comment by schaefi** [comment]
@ybaumy I've update the docs and hope this makes more sense now. Would be great if you can have a look. Thanks

**Comment by ybaumy** [comment]
thanks first of all for updating this. what I think is missing.. is the platform related information like tested on AWS/Azure/ or which platform. That would pretty much complete the table. But I understand if that would be too much.

**Comment by schaefi** [comment]
ok I have added some information about where KIWI built images are used productively and also some words about the supported architectures. The field here is huge so the information is based on the most actively used targets these days and for the rest people should get in contact with us.

Hope that makes sense to you too ? I let one of our doc guys do a review and will merge unless there are objections.

Thanks
