### ISSUE TITLE
Building in OBS and using "imageinclude" leads to wrong repositories in the resulting image

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#178]
## Problem description

OBS creates its own local repositories for each kiwi build, so kiwi runs as it was configured with local repositories, which leads to incorrect repo URL in the resulting image if `imageinclude` was set.

## Actual behaviour

A uri like: `obs://openSUSE:Leap:42.1` is included to the image as something like: `dir:///usr/src/pacakges/SOURCE....` which has no sense at runtime.

**Comment by mlschroe** [comment]
This is probably the wrong fix. There should be a way to make imageinclude work with obs builds.
Especially if we have real http:// urls is the repo and make use of the obs http->obs translation.
We really need this for creating docker images with configured repos. The repos could be added with some post-build hook that calls 'zypper ar' manually, but that's a horrible workaround.

I think the easiest way is to add a way to exclude a repository from being used for image creation. This is a useful thing to have: it allows one to specify a "imageinclude but excluded" repository, i.e. a repository that is not used to build the image but is configured in the resulting image.

When we have this, we can tweak obs so that it adds the untranslated imageinclude urls to the repository list via the command line.

**Comment by davidcassany** [comment]
I agree this is something that can be solved. Up to now in order to include the repositories we are including the .repo files inside the overlay tree tarball (the root.tar.gz) which is not that horrible, but of course not as good as being able to use "imageinclude".
I think (if I recall correclty) we just made this runtime check not make our uri translation class more complex and because we had no specific demand (note that many kiwi images in OBS make use of `obsrepositories:/` in which case imageinclude is not implemented and I don't think it would have much sense).

I also think that finding a way to state in the xml file some repositories to be included in the resulting image, but not used at build time can be an interesting feature. I think this idea, even being a different feature, is in line with #358, in the sense that we need some more granularity to handle repos.

> When we have this, we can tweak obs so that it adds the untranslated imageinclude urls to the repository list via the command line. 

I don't think this would be needed, but anyway this is a minor aspect.

**Comment by mlschroe** [comment]
Let me tell you where this is coming from: the native docker build folks want to be able to use kiwi generated base images. In order for this to work, we need to know what repositories are configured in the base image, so that obs can use them for setting up the needed repos. It's easy to get the information from the kiwi xml file, but much harder if it comes from some tree tarball.

(I don't think kiwi has the concept of "take repositories from base image" yet, but maybe it's something worth considering as well.)

**Comment by davidcassany** [comment]
> we need to know what repositories are configured in the base image, so that obs can use them for setting up the needed repos

I see, kiwi, at the moment, does not use the repositories configured in the base image to build a derived image, up to now this is left to the user responsibility to set the same or compatible ones. I guess you aim to solve it, this way only extra repositories would have to be included if necessary.
 
About that, during my hackweek some weeks ago, I did a patch to let kiwi use any already present and configured repository in the image at build time, this way, derived images could be done without setting any repository in the description file. At that time as I did not see a nice way to place it in the schema neither a clear use case, so I did not consider it for being a candidate to be included upstream. Maybe it is time to review it and see if it could help in any way.
