### ISSUE TITLE
config.sh is executing before repository setup

### ISSUE THREAD

**Issue by mkrawiec** [SUSE/kiwi#214]
## Problem description
If I'm not mistaken in kiwi v7 the flow was that it first initialized repositories inside an image and than call config.sh inside the image. Right now it is the other way around, so If i try to run `zypper --non-interactive --gpg-auto-import-keys refresh` the keys are not imported because the repos were not set up when script run.

## Actual behaviour
See [log](http://pastebin.com/7ZDCKhMv) of the build

## Steps to reproduce the behaviour

**Comment by davidcassany** [comment]
Certainly in KIWI v8 the command `zypper --non-interactive --gpg-auto-import-keys refresh` does not succeed if included in config.sh because as you noted config.sh is executed before including the image repositories.

This could be _solved_ by re-arranging some code lines from `kiwi/tasks/system_create.py` and `kiwi/tasks/system_prepare.py` (config.sh could be run right after the repository inclusion and delete/clean System object right after running config.sh). However I am concerned about including some ugly regression with such a change, specially in OBS where the repositories are handled quite differently. 

I will make a pull request with those changes just tot start the discussion as I am not sure this is a good option. Maybe we should handle that in a wider perspective, since the actual problem is to build an image with trusted repositories, right?
