### ISSUE TITLE
Allow setting of NoCOW attribute for btrfs subvolumes

### ISSUE THREAD

**Issue by thkukuk** [SUSE/kiwi#218]
## Problem description
Some btrfs subvolumes needs the "NoCOW" attribute to disable Copy-On-Write, e.q. the subvolumes for containers and virtualisation images. We need a way to set the attribute during creation.

## Actual behaviour
It's not possible and Copy-on-write will be used for databases, containers and images.

## Steps to reproduce the behaviour
Check with chattr (google for btrfs nocow) if it is set or not. Setting it should work with "chattr +C <subvolume>", but best is to ask the libstorage developer from the YaST team.

**Comment by schaefi** [comment]
https://btrfs.wiki.kernel.org/index.php/FAQ

**Comment by schaefi** [comment]
I'm going to work on this one next

**Comment by schaefi** [comment]
I have several questions to the attribute setup:

* is it required that the subvolume is mounted prior to call chattr on the mountpoint directory ?
* Is this a permanent setting or do we have to repeat it again and again ?
* If it is not permanent where must the information be stored so that it is handled at boot time ?
* If it is not permanent no-copy-on-write imho must only be set at boot time but not at image build time ?

I asked Arvin via mail

**Comment by thkukuk** [comment]
On Fri, Jan 20, Marcus Schäfer wrote:

> I have several questions to the attribute setup:
> 
>   • is it required that the subvolume is mounted prior to call chattr on the
>     mountpoint directory ?

You need access to the subvolume, it does not matter if it is mounted or not.
What will work ist:
chattr +C <mountpoint>/@/var/lib/etcd

>   • Is this a permanent setting or do we have to repeat it again and again ?

It is permanent.

  Thorsten

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & CaaSP
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)
