### ISSUE TITLE
lacking support for legacy init scripts in kiwi-ng

### ISSUE THREAD

**Issue by M0ses** [SUSE/kiwi#256]
## Problem description
The function "suseInsertService" checks if a service is installed. Finally the function "baseSystemdServiceInstalled" is used for this, but this function does not check for legacy init scripts in /etc/init.d

## Actual behaviour
Service do not get activated, even if installed.

## Steps to reproduce the behaviour
Install and try to activate packages with legacy init scripts (e.g. obs-server) with kiwi-ng

## Additional Information
SEE:
https://github.com/SUSE/kiwi/blob/master/kiwi/config/functions.sh#L39

**Comment by schaefi** [comment]
right because kiwi-ng does not support legacy init (sysV init) scripts. The distributions it supports are all using systemd and systemd itself aims for backward compatibility with sysV init scripts. Thus all code to deal with legacy init stuff has been removed from the next generation kiwi code base

Maybe I need more details on your use case

**Comment by M0ses** [comment]
Our use case:

Most of obs init scripts are legacy and handled well by systemd.
Checking only for systemd directories for service/mount files to determine if a service is installed or not might not be enough in legacy case.

**Comment by schaefi** [comment]
All right, finally understood the trouble. Please find the above pull request. A review would be nice 😄 

Thanks

**Comment by M0ses** [comment]
LGTM :-)
