### ISSUE TITLE
missing route for the NIC’s subnet

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#311]
## Problem description

Report from Smith, Randall B" <rbsmith@sandia.gov>

setupNetworkWicked in KIWILinuxRC.sh uses the ip command to configure the
route. It only configures the default route, it doesn’t configure the route for
the subnet associated with the boot NIC. So, in the ip route output below, the
second route is missing. If the PXEboot server is sitting on the 10.1.0.0/16
subnet, then the 10.1.1.254 gateway must allow routing over its 10.1.1.254
interface. In my case, I worked around the problem by adding a firewall rule to
allow routing from eth1 to eth1 on the 10.1.1.254 gateway.

```
$ ip route

default via 10.1.1.254 dev eth0 proto dhcp
10.1.0.0/16 dev eth0 proto kernel scop link src 10.1.100.38
```

I can add the subnet route via the hook. Just out of curiosity, is there a
reason why setupNetworkWicked doesn’t add the route entry for the NIC’s subnet?
Without it, the NIC can’t talk to other devices on its own subnet. It seems
common for OSes to set up this route by default.

**Comment by davidcassany** [comment]
I have done some tests and I am not sure this is something we should handle in KIWI. I coded a patch to add that route and while testing it I realized that my testing environment already has that route configured during boot. In my libvirt environment that route appears automatically after adding the default route, after running `ip route add default dev $PXE_IFACE` in _setupNetworkWicked_ method. I am wondering if could depend on the SUSE version or on the DHCPD configuration. Up to now I could not find a clue.

@schaefi would it be possible to request further information about the failing env? I can contact Smith if required.

**Comment by schaefi** [comment]
I came to the same conclusion you found. Actually the route exists if the ip addr call was made with the correct subnet specification. I looked at the code in kiwi and did not see how the call could have been performed without a subnet information. Thus I head out to Randall by mail and got some information back.

I did not had time to look deeper into that issue because of other tasks/meetings while I'm in Nuremberg. I'll forward you the mail communication

**Comment by davidcassany** [comment]
@schaefi maybe it is related to that issue, I have found some issue while trying to boot a pxe image in my environment. I was having problems to get the image file from the server, as the client was rejecting the packages coming from the virtual bridge. My setup is as follows:

* Have a VMX in a NAT libvirt network to use as the atftp server
* I have a VMX on the same libvirt network that is configured to netboot
* The libvirt network's DHCP server configured to point out the atftp server IP and pxelinux.0 image file.

With this setup if I try to netboot my pxe image the kernel and initrd are loaded without issues but this is not the case for the system image when the netboot code gets executed. I don't really know why the multicast gets disabled only to download the image file (in _fetchFile_ method of `functions.sh`), but that change makes my setup to fail, the atftp client fails with some messages rejecting the packages it gets from the virtual bridge (maybe libvirt does something strange with iptables to configure the virtual bridge and package source IPs get altered). If hacking fetchFile function not to disable multicast the image download works as expected.

Just wanted to share as maybe such a hack might solve Smith problem. @schaefi do you have any idea why the multicast option is disabled on the client side in order to download the image, but not for the rest of the files?

**Comment by schaefi** [comment]
>    [1]@schaefi maybe it is related to that issue, I have found some issue
>    while trying to boot a pxe image in my environment. I was having
>    problems to get the image file from the server, as the client was
>    rejecting the packages coming from the virtual bridge. My setup is as
>    follows:
>      * Have a VMX in a NAT libvirt network to use as the atftp server
>      * I have a VMX on the same libvirt network that is configured to
>        netboot
>      * The libvirt network's DHCP server configured to point out the atftp
>        server IP and pxelinux.0 image file.
> 
>    With this setup if I try to netboot my pxe image the kernel and initrd
>    are loaded without issues but this is not the case for the system image
>    when the netboot code gets executed. I don't really know why the
>    multicast gets disabled only to download the image file (in fetchFile
>    method of functions.sh), but that change makes my setup to fail, the
>    atftp client fails with some messages rejecting the packages it gets
>    from the virtual bridge (maybe libvirt does something strange with
>    iptables to configure the virtual bridge and package source IPs get
>    altered). If hacking fetchFile function not to disable multicast the
>    image download works as expected.

I have observed such issues in the past and they were all related to
the combination of the tftp server and the used client when multicast
was enabled on the server. Thus for bigger downloads like for the image
we disable multicast. In addition we recommend to put the image files
on ftp and use "kiwiservertype=ftp" in the pxelinux.cfg/... The kiwi
boot code will use curl in fetchFile to load the image and that has
been proven to be more stable especially on heavy load

Overall I think it's not related to the missing subnet route
might be wrong of course as I'm not an expert in this area

**Comment by schaefi** [comment]
Further information by mail

```
> Boot.kiwi is on a standalone network, so I copying this stuff by hand:
> 
> In KiwiLinuxRC.sh: setupNic(), is the command
> 
> ip addr add $address broadcast $netmask dev $iface
> 
> boot.kiwi reports
> 
> ip addr add 10.9.104.151 broadcast 255.255.0.0 dev eth1

That is something we have changed in kiwi

> According to the ip-address(8) man page, the syntax is
> 
> ip addr add ADDR broadcast ADDR dev STRING, where ADDR can be ADDR/PREFIXLEN.

right and looking to:

    https://github.com/openSUSE/kiwi/blob/master/modules/KIWILinuxRC.sh#L4940

This should be the way we are processing it. To my understanding the subnet
route can only be missing if no prefixlen was set or the ip comand is
called as you see it in your kiwi log

Would you mind to update to v7.04.30 from here:

    http://download.opensuse.org/repositories/Virtualization:/Appliances

imho that should address this issue
```

**Comment by davidcassany** [comment]
Thanks @schaefi I will have a look at that information. I will also give a try to KIWI v7.04, would be nice if the issue can be reproduced.

**Comment by schaefi** [comment]
I'm gonna close this one as I don't see a problem with the latest implementations
