### ISSUE TITLE
Hostname of built Ubuntu systems is the hostname of the kiwi builder instead of "localhost"

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#328]
## Problem description
When building Ubuntu systems with KIWI, the built image is set up with the hostname of the host system that built the image rather than "localhost". This can cause unexpected surprises when testing images on the same network where you built it and everything is accessed via SSH (as there would be a hostname collision on the network).

## Actual behaviour
Built image has builder's hostname set instead of generic `localhost`.

## Steps to reproduce the behaviour
1. Build Ubuntu Xenial description with vmx type on a system running kiwi with a notable hostname.
2. Boot the built image in a VM and notice that the login prompt has the hostname of the builder system.

**Comment by schaefi** [comment]
This is interesting yes, but there is no code in kiwi which deals with the hostname. Thus I guess the hostname setup happened due to some package script which I would consider a problem of the package. 

when building a suse image the hostname (/etc/hostname) is set to linux.local which is also done by some package installation.

I think you can handle the hostname setup as part of the config.sh script in your image description.
If the setup is generic enough to serve for all linux distributions we could also consider providing a method in the common config/functions.sh space

But in general I avoid system setup code as much as possible from being a builder responsibility with the exceptions of locale, timezone, hardware_clock, keyboard_map, users, groups and selinux context.
The keyboard_map part was a mistake from the early days which I couldn't get rid of any more :) All the others might have a bad impact on the ability to boot the image if not addressed as part of the build and that's why they are there.

**Comment by schaefi** [comment]
So the question is can you identify which part was responsible for the unexpected hostname setup and are you ok with handling the setup as part of the config.sh script ?

**Comment by schaefi** [comment]
feel free to re-open if this becomes an issue again, thanks

**Comment by Conan-Kudo** [comment]
@schaefi It's still an issue, I just don't know yet which piece is causing the problem.

**Comment by schaefi** [comment]
Any news on that one ?

**Comment by Conan-Kudo** [comment]
@schaefi I haven't had too much time to dig into it much. I _think_ there might be a trigger running that is setting it, but I'm going to try to take a look into it this weekend.

**Comment by schaefi** [comment]
This one is open for some time. For further planning I'd like to ask if the issue still persists and if so if there are further details which helps to sort this out.

Maybe this one is also solved by the changes done in #577 

If this one falls off the radar please let me know if it can be closed

Thanks

**Comment by Conan-Kudo** [comment]
I'm not sure how #577 affects hostname stuff? I'll check again with the latest code.

**Comment by schaefi** [comment]
@Conan-Kudo did you had a chance to see if we still have this problem ? Thanks

**Comment by Conan-Kudo** [comment]
This is still happening. My image I just built and booted has the hostname as `kiwi` (the name of the build machine).

**Comment by schaefi** [comment]
Could you check if /etc/hostname also contains "kiwi" as the hostname ? I guess this is not the case and furthermore I guess that the cached information from systemd-hostnamed somehow made it into the image. I'm not sure if we can prevent that though

You could consider a one-shot boot service which calls:

```
hostnamectl set-hostname ""
```

and that resets the selected hostnames to their default

In my tests with a Leap42.3 image the host has the hostname 'd16' from dhcp and the guest image has hostname set to 'linux' whereas /etc/hostname contains 'linux.suse'. I have not found what writes that setup and it's also different from my build host which has 'linux.site' in /etc/hostname

Overall this is quite confusing but I'm pretty sure kiwi itself does nothing with the hostname

As systemd controls the hostname as a service daemon we can't influence that at build time because it would affect the host.

I think this can only be addressed by an explicit hostname setup as part of the image description or a service which runs once at boot time.

If you think there is something we can do in the builder directly to make this any better feel free to re-open.

Thanks and sorry for the late response
