### ISSUE TITLE
hybrid iso images don't work when syslinux versions in host and image differ

### ISSUE THREAD

**Issue by msrex** [SUSE/kiwi#351]
Trying to build a hybrid iso for Fedora 26 Beta on an openSUSE Leap 42.2 host. The syslinux version on openSUSE is 4.x based, whereas Fedora and Ubuntu upgraded to syslinux 6.x.

The problem: paths of some isolinux-files have changed between the two versions. No booting is possible.

When building a hybrid iso for CentOS 7 (where the syslinux version 4.0.5 + patches is at least similar to SUSE's 4.0.4 + more patches) I can create a bootable image that does everything as desired. Yeah!

**Comment by schaefi** [comment]
Not sure if we can address this in a clean way in the kiwi builder. In general I think it would be a good idea to prevent cross distribution builds, meaning if the target is e.g fedora the build host should also be fedora. my dice project http://suse.github.io/kiwi/building/build_containerized.html goes into that direction. We could think of creating build containers for different distros

Thoughts ?

**Comment by Conan-Kudo** [comment]
I suspect that's just making it more complicated. It's probably quite easy to identify whether something is syslinux 4 vs syslinux 6.

At the simplest level, you can query via the package manager (`rpm` or `dpkg`) about whether it's syslinux 4 or 6 and handle it differently.

Alternatively, you can check for the existence of files that only exist in syslinux 6 and fall back to syslinux 4 behavior when they don't exist.

**Comment by schaefi** [comment]
if we have a really safe way to distinguish both cases I'm open to support the syslinux case
@msrex could you provide more details on the path changes and what exactly means "some isolinux files" which one do you refer to ? in kiwi I use `isolinux-config --base` to configure the base path thus I guess we are talking about other differences ?

> I suspect that's just making it more complicated.

It's true an encapsulated environment adds another layer on top of the build, that makes the setup more complex but the result more reliable.  At some point there will be a situation where we can't easily come up with a compatibility patch or it will be too complex, too hard to maintain or not worth the effort to hook the code into kiwi. At that point it is a good idea to think about a controlled build environment which would allow to avoid dealing with issues which only exists due to differences within the distributions

The buildservice does this for all targets, packages and images to even avoid inconsistencies between the distro versions of the same vendor :)

**Comment by Conan-Kudo** [comment]
Yes, but OBS kiwi doesn't work for anything but SUSE right now for other reasons (still trying to work those out...)

**Comment by msrex** [comment]
@schaefi The files in `/usr/share/syslinux` changed. Some of the `*.c32` files are new or changed names. When you then call the `syslinux`-command the installed code expects the files from the system of the caller. In this case the host system. `linux.c32` is very different size, and `ldlinux.c32` is only part of the newer syslinux version.

If there is any chance of calling the image-version of the tools in a chroot that would solve the issue. You could mount the kiwi-created initrd inside the image-root instead of `/tmp` and then call `syslinux` chrooted and pointing to that location.

**Comment by Conan-Kudo** [comment]
Well, calling it in the chroot would work, except `isolinux-config` is like shim-install where a SUSE guy wrote it, and it's not available elsewhere. The good news is that it looks like it's relatively clean and might just work on syslinux 6 on Fedora. Will have to check...

**Comment by schaefi** [comment]
Uhm you are right isolinux-config is a suse only thing :( ok we have to address this one. Thanks for the details. Do you have a Fedora26 image description (or repo setup) which I can take for testing an image build ?

**Comment by schaefi** [comment]
poor attempt to get the version, I'm open for better ideas

```
$ strings /usr/share/syslinux/syslinux.com | head -n1
```

**Comment by schaefi** [comment]
Still trying to search where I can find a fedora26 release repo to build an image from

**Comment by Conan-Kudo** [comment]
Here, I've attached a converted version of the F25 kiwi to F26 that should work.
[fedora-26.0-JeOS.tar.gz](https://github.com/SUSE/kiwi/files/1061175/fedora-26.0-JeOS.tar.gz)

**Comment by Conan-Kudo** [comment]
In addition, Fedora 25 also uses syslinux 6 instead of syslinux 4.

Fedora switched to syslinux 6 in Fedora 21.

**Comment by schaefi** [comment]
ok so I should be able to reproduce the issue by building a live iso from the fedora25 image description. I'll do that next and report back

**Comment by schaefi** [comment]
Ok I can reproduce this...

**Comment by msrex** [comment]
I just verified that Fedora 26 and Fedora 25 indeed behave the same.

**Comment by schaefi** [comment]
Found the problem the lib modules were not present
