### ISSUE TITLE
Port initrd-image building from kiwi 7

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#382]
## Problem description
In kiwi-ng it is not longer possible to build the initrd image standalone.
## Actual behaviour
Fails with:
`KiwiRequestedTypeError: requested image type cpio not supported`
## Steps to reproduce the behaviour
- Copy the files from https://github.com/SUSE/kiwi/tree/master/kiwi/boot/arch/x86_64/oemboot/suse-SLES12
- Try to build it (We use OBS)
-  Fails with: `KiwiRequestedTypeError: requested image type cpio not supported`

> < schaefi> The support for building standalone initrd (boot images) has not been ported over from kiwi v7 to the next generation code base. As David
                    said the building of the initrd image is an internal task which is connected to the image build which needs this.
> < schaefi> it would be easy to populate this build process to the user end but I need to understand the use case, actually a standalone initrd only makes sense for e.g pxe images where kiwi
                    provides it as part of the build

**Comment by schaefi** [comment]
Also from the irc discussion:

In general the reason for not providing a standalone initrd build is the missing connection to the system image this initrd should boot. The kernel and the kernel modules of that initrd has to match the system it should boot. If this is not the case  the user runs into trouble at boot time at the point a kernel module should be loaded from the active system.

Therefore I'm not too enthusiastic to add this capability into kiwi even though it is not too hard from a technical perspective. In order to come to a conclusion we need to discuss the use case and the possible existing alternatives for a more clean setup

As far as I understood the image you are building is a pxe image with a customized initrd. The way we support this in kiwi is as follows:

1. package your custom initrd description (probably based on the netboot description we provide) and
    let the package install the custom initrd description to `/usr/lib/python*/site-packages/kiwi/boot/arch/*/netboot/your-netboot`

2. reference your boot code in your image description via `boot="your-netboot"`

3. build your image as pxe type using the `installpxe="true"` attribute which will create a tarball of the image containing, the initrd build, the system image build and the kernel which were all built from the same repository and thus forms a compatible entity for use in the pxe deployment

I need to understand if that workflow suits you and if not why it is not applicable to your use case

Thanks

**Comment by Jellyfrog** [comment]
I would say this solves it, only minus is that you have to wait for a full build.

**Comment by aplanas** [comment]
I am planning to create a initrd for pxe-boot that contains salt-minion, and I do not need a rootfs for this image. I want to understand the work-around described here:

>     1. /usr/lib/python*/site-packages/kiwi/boot/arch/*/netboot/your-netboot

Is this some Python code that is already dropped? Is this still a valid work-around? Do you have any link for an example of a custom-made initrd done in this way?

**Comment by schaefi** [comment]
@aplanas if you need a special initrd I suggest to write a dracut module that does what you need and integrate that into a kiwi build. The SLEPOS team at suse did something very similar to what you are aiming for. Check this out:

* https://gitlab.suse.de/SLEPOS/SUMA_Retail/blob/master/dracut-saltboot/saltboot/m
odule-setup.sh

In kiwi you can't build an initrd only because we are building systems and an initrd only doesn't represent one. So the simplest image type you can set is:

```xml
<type image="pxe" filesystem="ext3" initrd_system="dracut"/>
```

actually for building a dracut initrd you need a system environment to create it. That kiwi builds a rootfs image is a plus but if you don't need it just don't use that data.

Hope that helps

**Comment by aplanas** [comment]
@schaefi excellent, thanks!
