### ISSUE TITLE
Make imageonly work in OBS

### ISSUE THREAD

**Issue by davidcassany** [SUSE/kiwi#393]
## Problem description

Make imageonly work in OBS. This can be really handy for Docker base and derived images, also other types can take benefit of it by having an easier more explicit way of defining the resulting configured repositories in the image (now it is done by repo files inside root.tar.gz).

Having a look at @mlschroe comments [here](https://github.com/SUSE/kiwi/issues/178#issuecomment-305433779) I also think it would be handy to find a way to make `imageonly` work in OBS. I believe this includes changes in KIWI and some small changes also in OBS to make sure any imageonly repository is simply completely ignored.

I forsee the possibility of having something like:

```xml
<repository>
  <source path="obsrepositories:/"/>
</repository>
<repository type="rpm-md" imageinclude="true">
  <source path="http://download.opensuse.org/tumbleweed/repo/oss/suse/"/>
</repository>
```

@mlschroe, @schaefi what think about that, does it makes sense to you?

## Actual behavior

`imageonly` in OBS seams to be erratic at the moment

**Comment by davidcassany** [comment]
@schaefi I have retracted of trying to provide support of `imageinclude` in OBS as I do not see any way of achieving it that does not include some ugly hacking or code coupled with some concrete OBS instance.

**Comment by schaefi** [comment]
I think you are referencing the following as a problem

```python
<repository imageinclude="true">
  <source path="obsrepositories:/"/>
</repository>
```

for those the buildservice doesn't have an interface to the imaging world, and that's imho required whenever data from the project configuration needs to be taken into account. I agree we should not invest too much time with this part.

for repository specifications which includes a source path not referencing another data source I think imageinclude should work today, or am I overlooking something ?

what I don't know is if the buildservice continues to evaluate a repository section even if it is marked as imageonly

**Comment by davidcassany** [comment]
Well, yes

```xml
<repository type="rpm-md" imageinclude="true">
  <source path="obsrepositories:/"/>
</repository>
```
is a problem, imho it should not be permitted, too confusing and it might lead to unexpected repository configuration on the resulting image.

My intention is to be capable to define image repos inside of OBS without having to include repo files in root.tar.gz, recently I had some complaints about that.

>for repository specifications which includes a source path not referencing another data source I think imageinclude should work today, or am I overlooking something ?

I have not tested exaclty this specific case, I guess it might work in remote buildservice. Trying to make it work locally using `osc` I noted that OBS and kiwi do not coordinate properly when using regular http urls for rpm-md repos. OBS understands the urls and sets the appropriate repos in the build env, but does not override the repo configuration of KIWI, thus KIWI at build time stills tries to pull from the net all repos, which is just not possible in OBS. But well I guess this is a such a corner case that might need some little osc improvement.

>what I don't know is if the buildservice continues to evaluate a repository section even if it is marked as imageonly

Yes buildservice still takes into account the repositories marked as imageonly and it shouldn't. My idea is that using imageonly could be a good way to include explicit arbitrary repositories to the image in OBS without having to use custom files in root.tar.gz or without having to make specific zypper calls in config.sh. I have retracted about being capable to use imageonly in OBS because kiwi is not capable to translate `obs` scheme url to the correspondent buildservice download host when running inside OBS.

**Comment by schaefi** [comment]
> obsrepositories and imageinclude, imageonly is a problem and should be forbidden

yes, let's do that, it could be a separate issue (runtime check). imho I see several issue here which we could split up a little bit

> My intention is to be capable to define image repos inside of OBS without having to include
> repo files in root.tar.gz,

I agree and that's why we have this imageinclude attribute. For building in obs the url is translated
into a path but for inclusion into the image the information from the XML description is taken into account. Thus for all repos which are http resolvable this should work. We have a runtime check
in check_image_include_repos_http_resolvable() which checks this condition and I guess that's what
bites you when using e.g repos from the internal buildservice, correct ? I'm not sure if we will be able to find a solution here without an api in the buildservice but just for my own reference can you point me to the project which has this tarball containing repo files ?

> Yes buildservice still takes into account the repositories marked as imageonly and it shouldn't. 

that what I thought too, imho of not done we should open an issue on the buildservice github to ignore those entries.

> My idea is that using imageonly could be a good way to include explicit arbitrary repositories to the
> image in OBS without having to use custom files in root.tar.gz

That sounds good good to me

> I have retracted about being capable to use imageonly in OBS because kiwi is not capable
> to translate obs scheme url to the correspondent buildservice download host when running
> inside OBS.

But that it should be able to do. For the public obs repos that should happen automatically and for
the internal repos you need to pass in the option --obs-repo-internal to kiwi. If there is a bug that should be fixed

**Comment by davidcassany** [comment]
OK, I am trying to summarize the concrete tricky case.

Having repositories like:
```xml
<repository type="rpm-md" imageinclude="true">
  <source path="obs://openSUSE:Leap:42.2:Update/standard">
</repository>
<repository type="rpm-md" imageinclude="true">
  <source path="obs://openSUSE:Leap:42.2/standard">
</repository>
```
Fails in OBS, check_image_include_repos_http_resolvable fails if imageinclude is used inside OBS (see the fix for #178). Before including that fix the problem was that the local repositories used in OBS builds were included (repos in `/usr/src/PACKAGES...`).

My first attempt or idea to solve this was to include an additional condition in the kiwi/system/uri.py to translate with a different criteria when using it inside import_repositories_marked_as_imageinclude method. But this is not possible, because kiwi when is runs inside OBS, never knows in which OBS instance is running (OBS, IBS or any other OBS deployment), thus it doesn't have information enough to make the appropriate `suse` -> `http` translation. In that situation if we make some kind of the best guess, we could end up breaking KIWI usage in non SUSE or non openSUSE buildservice instances.

The point is that KIWI doesn't need to know the URI or host of the buildserice instance is running in to make use of the buildservice repositories, this is a very good thing and must be preserved.

To my understanding the flag `--obs-repo-internal` only makes sense when using kiwi out of the buildservice.

**Comment by davidcassany** [comment]
Also I am perfectly fine to split that discussion into multiple issues once we have common understanding of what makes sense and what can be done.

**Comment by schaefi** [comment]
Ok thanks for the details, now I got it. Did a short test with an osc build command and yes you are right the translation path for an obs build is only suitable for the build in the worker but not to become included as repo in the image. Our runtime check just kicks us out, intentionally at this place

If there wouldn't be the separation between internal and external buildservice it would be possible to add a switch to the translate() method, but that would result in a confusing state and also won't work for ibs repos.

Thus I would say we should:

* keep the runtime check and kick us out if someone tries to imageinclude repos when we build in the buildservice. However we can make the message from the runtime more clear and say that one should explicitly create repo entries marked as imageonly when building in the buildservice. I also have tested the imageinclude together with obsrepositories and that also caused the runtime check to cry which is good

* Use the imageonly attribute to setup a custom repo setup for the image itself. This imho implies no changes on the kiwi side but the buildservice has to ignore those for its own setup

That's where I'm stuck with my testing now because bs tries to evaluate what I added as imageonly :)

**Comment by davidcassany** [comment]
I mostly agree on everything 😄

The only note I would make is that I believe some minor changes are still needed in KIWI to make it completely useful. I believe the `--ignore-repos` flag should only ignore the repositories used for build, at least this is what makes more sense imho. This way we could do something like I suggested before: 

```xml
<repository>
  <source path="obsrepositories:/"/>
</repository>
<repository type="rpm-md" imageinclude="true">
  <source path="http://download.opensuse.org/tumbleweed/repo/oss/suse/"/>
</repository>
```

Buildservice uses `--ignore-repos` flag to set the build repositories, I believe imageonly repositories should not be affected by that flag. But well, this is just an opinion, just a matter of deciding which is the expected behavior.

**Comment by schaefi** [comment]
yes good catch, you are right that has to be changed in kiwi

**Comment by schaefi** [comment]
So could you open an issue for us to fixup the behavior of ignore repos and also create an issue for the buildservice people to ignore imageonly repos ?

I would consider this issue done when the other two issues have been opened :) that's funny

**Comment by davidcassany** [comment]
All right, let's do it that way ;) I am on it

**Comment by schaefi** [comment]
👍 :)

**Comment by mlschroe** [comment]
But with the  "--ignore-repos flag should not delete imageonly repos" commit, you also need to internally switch "imageinclude" repos to "imageonly" repos, so that those work as well.

**Comment by davidcassany** [comment]
@mlschroe  That's an interesting idea, even I am not sure I can see a use case for that.

The main idea behind removing the `imageinclude` support when running inside the buildservice is that KIWI will not have enough information to make the URI translation happen, because KIWI is unaware of the buildservice instance details (doesn't know about being inside OBS, IBS or anywhere else). When running inside a build service instance KIWI translates any `obs://` style URI to a local path, which will be the same regardless of the buildservice instance.

Then if `imageonly`  repositories are ignored by the buildservice we can use them to include any arbitrary repository into the image, assuming they are set with the correct URI that doesn't need any translation or that it can be properly translated.

**Comment by mlschroe** [comment]
You're missing my point. I want 'imageinclude' to work in OBS as well. Since we added repo mapping, you can use normal `http://` urls as source instead of using `obs://`. In that case it makes perfect sense to use the `imageinclude` attribute.

Having thought about this a bit more at lunch, I think another option is to revert the "--ignore-repos flag should not delete imageonly repos" commit and instead rely on obs adding back the imageonly/imageinclude repos via the command line. That way we can even support `obs://` and `obsrepositories:/` style repos with the `imageinclude` attribute (obs would map them to `http://` urls). The downside is that all repository attributes must be configurable via the command line, though, which I think is currently not the case.

Make your choice ;)

**Comment by davidcassany** [comment]
All right, then I think I need to make some more tests in order see which are actually the options we have, I am little confused now about how buildservice handles repositories and this new features.

I'll prepare some tests and share the project with several trials, this way we can discuss on concrete reference examples with the appropriate build to test. I think is going to be the easier way to make sure we are on the same page and that everything works as expected.

**Comment by schaefi** [comment]
Ok so we are starting to mix things up which should be avoided:

> You're missing my point. I want 'imageinclude' to work in OBS as well. Since we added repo 
> mapping, you can use normal http:// urls as source

Sounds good but that needs a change in kiwi because we don't allow imageinclude in general if
Defaults.is_obs_worker() returns true. @davidcassany could you open a new issue that we want to
support this in kiwi ? thanks

> I think another option is to revert the "--ignore-repos flag should not delete imageonly repos...

repos marked as imageonly basically defines the repo setup inside of the image if this can't be 1:1 mapped via the imageinclude flag set to the repos building the image. The repo options set on the commandline are exclusively used to setup repos for building the image, that's why I think it is the right way for kiwi to ignore repos specifically set for the image only. The buildservice imho should do the same

> Having thought about this a bit more at lunch...

Your lunch time idea has a point here, I like the idea to allow setting the imageinclude flag along with the --add-repo option on the commandline. This would be yet another issue which we can address in kiwi. @davidcassany mind to create this issue too ?

**Comment by schaefi** [comment]
Last but not least I still think the buildservice should do us a favor and ignore repos marked as imageonly. @mlschroe could you do that for us ? Thanks

**Comment by davidcassany** [comment]
@schaefi yes sure, I will create those issues. About the imageonly on the buildservice side @mlschroe already did it in https://github.com/openSUSE/obs-build/commit/91c070ae9c32c5ab60e4fc14bd90dd325f03feae 😃

**Comment by schaefi** [comment]
great thanks David for opening the issue and thanks @mlschroe for the quick turnaround

imho this one can be closed now

**Comment by davidcassany** [comment]
yes agree, I am closing that one, thanks to all
