### ISSUE TITLE
Add post build constraints

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#468]
## Problem description

A discussion by mail brought up the idea to allow to setup general post build conditions in the kiwi config file like:

```yaml
build_constraints:
  - max_size: 2g
```

which causes kiwi to fail if one of the conditions is not fulfilled

## Actual behaviour

post build constraints does not exist

**Comment by schaefi** [comment]
I haven't received any feedback if idea of post build constraints is mandatory or important, thus we'll lower the prio for now

**Comment by Conan-Kudo** [comment]
This would actually be really cool, as when we're trying to make images that fit on USB sticks or SD cards of certain sizes, it's hard to tell if that's actually going to be the case until after the image is created.

**Comment by schaefi** [comment]
yes it will come, it just did not yet make it into the prio queue

**Comment by davidcassany** [comment]
@schaefi, I have a first implementation of that feature, I did the first straight forward implementation that came to my mind and some questions arised. My first attempt is to verify that no file included in a Result instance is bigger than the configured maximum size. This is simple, but I am wondering if this is what we want, as in order to make quick tests I have been trying it with a docker build and I realized that this way we are just validating against to the compressed image, which in this concrete case it doesn't have much sense I'd say.

Then I have been wondering if it wouldn't it be better if we had some kind of method like `Builder.get_size()` that returns the image size (this way we could calculate the image size with specific logic for every builder class), assuming that any kiwi builder inherits from a BaseBuilder class. Asking because it would imply some refactoring in builder classes to make them inherit from the same base class.

Another question that came to me is if we should try to find some strategies to fail early or earlier (like fail if the build-root is already bigger), I'd say this is not worth since is hard to find a common criteria for all image types, just wanted to make sure we are on the same page. Up to now I'd wait until the image is built to verify the constraint.

Any thoughts?

**Comment by schaefi** [comment]
I see the concern and agree. Instead of using a base class for every builder we could also think of using the already existing Result class: kiwi/system/result.py

Any builder registers it's individual results to an instance of Result. Thus is should be possible to also register the relevant size as a value in the Result instance. imho this is less code than refactoring the builders with a base class and it feels natural that the size of the image is part of the result.

The constraint checker would then only operate on the information in the Result instance

The Result instance is also pickled and can be retrieved at any later time like the "kiwi result list" command does it

Thoughts ?

**Comment by davidcassany** [comment]
I agree with the idea of registering the size into the Result instance, I'll refactor my current code include the size calculation within the builder and include it into the result instance, this way we'll have more accurate results.
