### ISSUE TITLE
Old .kiwi files do not build anymore after live iso rewrite

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#498]
```boot="isoboot/tumbleweed" type="iso"``` results in an error that ```boot=``` is not supported anymore.
After removing that, it complains about missing ```dracut-kiwi-live``` in the packages section.

This should be handled in a schema update xsl.

**Comment by schaefi** [comment]
The schema style and layout has not changed which is the reason why I did not change the schema version and no xsl stylesheet was provided. The type constraints changed and additional packages depending on the type are needed. Both conditions are handled by a schematron rule and by runtime checks with hopefully clear checker messages to guide people through the needed changes.

I thought about an auto migration but decided not to do so because package names can change and people should be made aware that a move in technology had happened.

I'm afraid but yes it needs a few fingers on the computer to move the image description from kiwi boot code to dracut+kiwi-modules boot code, that should not be done completely automatic

Hope that makes sense to you

**Comment by Vogtinator** [comment]
Thanks for the reply. I still think that this is the wrong approach though.

> I thought about an auto migration but decided not to do so because package names can change and people should be made aware that a move in technology had happened.

Well, that equates to screwing up the grub.conf every time a kernel version update gets installed.

> I'm afraid but yes it needs a few fingers on the computer to move the image description from kiwi boot code to dracut+kiwi-modules boot code, that should not be done completely automatic

IMO if anything breaks it's a regression in kiwi itself and needs to be fixed anyway.

**Comment by probonopd** [comment]
This is also bugging me.

Since some time my formerly perfectly working ISO is not building anymore, as significant parts of the Kiwi Live ISO system seem to have changed and I don't know how much I need to change and where.

```
[  630s] + sed -i -e 's,label Failsafe.*,label linux,' 'boot/*/loader/isolinux.cfg'
[  630s] sed: can't read boot/*/loader/isolinux.cfg: No such file or directory
```

It is really hard to keep up with a moving target. Will this be stabilized soon, and is there documentation how to make it work again? Thanks.
