### ISSUE TITLE
Live ISO not building anymore since recent changes

### ISSUE THREAD

**Issue by probonopd** [SUSE/kiwi#506]
Since some time my formerly perfectly working ISO is not building anymore, as significant parts of the Kiwi Live ISO system seem to have changed and I don't know how much I need to change and where.

For example:

```
[  630s] + sed -i -e 's,label Failsafe.*,label linux,' 'boot/*/loader/isolinux.cfg'
[  630s] sed: can't read boot/*/loader/isolinux.cfg: No such file or directory
```

Is there documentation how to make it work again? How do I know how many errors I will run into after this one, and how many other changes I need to make? It would be great if there was some documentation that would list _all_ changes that need to be made to make Live ISOs work again.

Also, it is really hard to keep up with a moving target. Will this be stabilized soon? And can we expect it to continue to work for some while (years rather than days) thereafter?

References:
* https://build.opensuse.org/package/live_build_log/home:probono:branches:KDE:Medias/openSUSE-Argon/images/x86_64
* https://build.opensuse.org/package/show/home:probono:branches:KDE:Medias/openSUSE-Argon

**Comment by schaefi** [comment]
Well isn't this a little bit unfair ?

I told people more than thousand times that using a custom edit_boot_config.sh can be done but is not save and I'll not accept complains when this is not working in a stable way, because it's your code that failed not mine.

* editbootconfig="/usr/src/packages/SOURCES/isopatch.sh"

yes man with dracut the caller environment has changed. The information where the iso structure can be found is passed to the script call as a parameter: In my test this was:

   iso:/tmp/mytest/live-media.6a_7pkun

so your script could be more robust with

```bash
location=$1
iso_dir=${location#iso:}

iso_config=${iso_dir}/boot/*/loader/isolinux.cfg
```

And again custom edit boot config scripting is considered a last resort solution if there is no better solution available. There are many many many many pitfalls one can run into by patching the boot config. That's why this "feature" is not documented and I tell everybody to use on their own risk.

Instead of complaining that something you used on your own risk now broke after the, if I read it
correctly expected years of no problems, it would be imho wiser to stop pointing fingers especially if it falls back to your own extension

Thanks

**Comment by probonopd** [comment]
Sorry @schaefi if I sounded too harsh. In fact I simply copied a (at the time) working image I liked (KDE Argon) and customized it from there. If I can drop `isopatch.sh` altogether I am all for it. Can I?
