### ISSUE TITLE
Kiwi image that runs from a VFAT USB-Stick

### ISSUE THREAD

**Issue by rakoenig** [SUSE/kiwi#521]
## Problem description
Want to create a sort of swiss army knife that boots openSUSE from an USB stick and then performs maintenance operations on the booted system, like updating BIOS or DMI information with factory tools. 
Problem is that target users often just have a Windows PC and want to have a stick where they can put new BIOS versions. That means the stick should be FAT formatted so that Windows can write on it.

Currently I tried two approaches:

1. Create an type="oem" image with a spare partition. That seems to work, but plugging this into a Windows machine asks the user if all the linux partitions should be formatted. And some people also said they don't see the spare partion, even if its formatted with vfat. 

2. Create an type="iso" image and put this on the stick. But then the stick has a linux file system and a second partition for the "cow" function is created to get the changes in the live system.

## Expected behaviour
You can add files by copying them to the stick which is on a FAT partition.

**Comment by davidcassany** [comment]
@rakoenig you can check #585 PR, it should mostly solve this issue.

**Comment by schaefi** [comment]
Yes with iso-scan now available this also makes live-fat-stick to work with it

* https://software.opensuse.org/package/live-fat-stick

We should mention that in the documentation. Thus I'll keep this one open. The docs will receive a bigger change in the next days due to our effort to move all custom kiwi boot code to dracut
