### ISSUE TITLE
Support vagrant box creation for virtualbox provider

### ISSUE THREAD

**Issue by serjk** [SUSE/kiwi#532]
Hello

I’m trying to create virtual box image. I’m using "<vagrantconfig provider="virtualbox" virtualsize="16”/>”. As far I understood, fresh kiwi supports only libvirt provider "<vagrantconfig provider="libvirt" virtualsize="16"/>"  but the legacy kiwi(perl version) supports libvirt and virtualbox.

Would be great to support virtual box image.

**Comment by schaefi** [comment]
I agree it would be nice. The reason why the next generation kiwi lacks support for the virtualbox provider of vagrant box images is that I was looking for an open project which supports the creation of the ovf format which is needed for running the box in virtualbox and still can't find a good one.

In the legacy kiwi I had my own code to create the ovf metadata and this was basically broken design from the beginning on because any change in the ovf setup of the target falls off the radar and required us to constantly change our ovf creator. In addition ovf is different depending on the target system, vmware, virtualbox, powervm... and kiwi just covered a small part according to its own use case.

Serving the ovf standard has potential to be its own project and kiwi is the wrong place for it. Thus I put my hopes into the Open-OVF project but that seems dead

The documentation from vagrant how to create a base box for the virtualbox provider is based on a machine running in virtualbox and I guess (did not had looked at the code) that they use the api from virtualbox to export a machine into an image

* https://global.gotomeeting.com/join/420314285

Obviously you could do this as well by creating a box for libvirt with kiwi, extract the raw disk image from it and boot that in virtualbox. Once up you can call

* vagrant package --base my-virtual-machine

But I agree this is not the way we want to have it. If virtualbox comes along with a tooling or an api we could use as part of the image creation process to create the required box.ovf we could integrate that into kiwi.

I also remember the binary only ovftool from VMware but apart from the fact that it's a closed source tool I even can't tell if it is able to create virtualbox compatible ovf files from the vmdk image kiwi would create.

So there are a few options which I'm not very happy with because they all point to closed source code and maintaining our own ovf creator is beyond the scope of kiwi

I have to admit that my information is not up to date, thus the situation could have changed since the last time I worked with vagrant and the virtualbox provider. If you can do some research and check the situation around ovf creation it would be very much appreciated.

If we find a way without writing a custom ovf creation toolkit I'm open for an implementation

**Comment by schaefi** [comment]
any Thoughts ?

**Comment by dcermak** [comment]
Since I started to work on this in #947, I'd like to discus a few open questions about this:

### How should the virtualbox folder share be handled? 

Virtualbox will by default try to share the `/vagrant/` folder as `vboxfs`, but that only works if the vagrant box has the Virtualbox guest additions installed. Detecting their existence is imho not the right approach, instead I'd suggest we provide an XML option for the image creator to specify whether they installed the guest additions. If they did, we will use the standard `Vagrantfile`, but if they didn't, we'll override the shared folder type from `vboxfs` to `rsync` (and maybe emit a warning if rsync is not installed, although vagrant will try to install it if not found?).

### How should the virtualbox CIMOS id be handled?

The ovf file inside the vagrant box contains an operating system ID field. How should kiwi handle this?

@Conan-Kudo said that various distros patch Virtualbox so that we cannot really rely on the official ID list from upstream's source. Thus choosing a sensible default is probably the only viable solution. But what should that default be? `Ubuntu_64` that packer uses or `Other Linux 64`?

We could provide an option for the image creator to override our default with an explicit warning. Although this will probably not get used a lot.


### Could kiwi build different vagrant boxes for the same image?

This is actually not virtualbox specific, but appeared during testing: what if I want to create a libvirt & virtualbox vagrant box from the same appliance?

Do we want to support this? I think that this can be useful, especially if the boxes should really only differ by the provider. Nevertheless, with virtualbox & libvirt these two will almost always differ, since virtualbox will need the guest additions, which are just wasted space in a libvirt box.
