### ISSUE TITLE
Fail to build live ISO with rpm and new RPMDB location

### ISSUE THREAD

**Issue by DimStar77** [SUSE/kiwi#537]
RPM was changed the location for the rpmdb, out of  /var/lib to /usr/lib; this change is also in accordance with upstream.

Since this change, though, we are not able to produce live images, since the kiwi build process fails, as can be seen at:

https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Live/livecd-gnome/images/x86_64

I am not (yet) sure if this is a pure kiwi issue or if there is also an rpm component to this bug (but would definitively appreciate the kiwi side of things to be validated)

**Comment by davidcassany** [comment]
@DimStar77 , to my understanding this is a problem of the `rpm` package posttrans scripts:

`warning: %posttrans(rpm-4.13.0.1-8.1.x86_64) scriptlet failed, exit status 1`
and 
`rmdir: failed to remove 'var/lib/rpm': Directory not empty`

It happens during the bootstrap install, which is not called in a chroot environment, is done using `zypper --root <build-dir>` and other flags pointing to the specific package manager config files. Not sure how the `--root` flag of zypper has effect over the internal rpm environment settings, but it looks like installing rpm package using `zypper --root <build-root>` is causing some issue related to the rpmdb change.

**Comment by DimStar77** [comment]
Thanks @davidcassany - from what I see it actually already fails on the rpm %post scriptlet (not %posttrans) ( and @sysrich should be looking into those)

On the other side, I'd seen kiwi referencing var/lib/rpm in various places too (functions.sh and strip.xml) and was wondering if kiwi might still need/want to adapt to the RPM db location change in the end too

**Comment by sysrich** [comment]
@davidcassany `zypper --root <random location> in rpm` works fine, so this is something specific caused by kiwi - Investigating. What does kiwi do during it's bootstrap install? is it injecting files willy nilly into /var/lib/rpm and not checking the rpm dbpath?

**Comment by davidcassany** [comment]
@sysrich, @DimStar77, right I am having a closer look. I'm trying to reproduce it locally. I found few `var/lib/rpm` references in kiwi code, mostly related to the oemboot code, which is about to be deeply refactored right now.

**Comment by DimStar77** [comment]
for reference: the correct db path should be queried to rpm, using, for example: ```rpm -E %_dbpath```

**Comment by davidcassany** [comment]
@DimStar77, great, thanks for the tip

**Comment by sysrich** [comment]
@davidcassany ignore what I said about --root working, bad test on my part, able to reproduce problems on a clean `zypper --root` digging into that also  - still think it'll be a good idea to tune up kiwi :)

**Comment by davidcassany** [comment]
@sysrich, sure, kiwi's references to var/lib/rpm must be updated using @DimStar77 hint if possible

**Comment by sysrich** [comment]
patched the %post symlink in rpm package in Factory to workaround this issue for now

Not only does kiwi need to fix it's var/lib/rpm references, we found one that zypp seems to do itself, so that's going to need to get fixed too :) Thanks for your help @davidcassany , your observations really helped put us on a fast track to workaround this

**Comment by schaefi** [comment]
Also see #1066612 in suse bugzilla

several areas needs to be patched, kiwi is only one component

**Comment by schaefi** [comment]
an implementation supporting both places is required. If this is not possible for whatever reason we have to create a runtime check which forbids rpmdb init between incompatible versions. Which would mean suse TW can only be build on a suse TW host

....and again my question why people think it's a good idea to move a directory existing for years just because of what ? some standard ? oh yeah let's change this it will create tons of problems how nice

**Comment by DimStar77** [comment]
the move    was definitively not done 'because of standard'
See https://lists.opensuse.org/opensuse-factory/2017-10/msg00047.html

it is actually SOLVING issues

**Comment by DimStar77** [comment]
The issue was resolved in RPM's own postscript (it created invalid symlinks)

As kiwi is supporting distros in a matrix, it's likely too high risk for kiwi to change paths in its current setup, or a TW host won't be able to produce other images anymore (kiwi on TW would setup /usr/lib, but rpm on older target images would not cope with it)

As a consequence: closing this issue (rpm fixed / kiwi wontfix)

**Comment by Conan-Kudo** [comment]
The path being used for the rpmdb is wrong (for SUSE, it will be `/usr/lib/sysimage/rpm`. Moreover, since `/usr/lib/rpm` always exists, it never backs up the rpmdb in `/var/lib/rpm`.

What makes this worse is that the rpmdb can be literally anywhere. It's defined and evaluated by rpm in the `%_dbpath` macro, so the correct way to figure this out is to evaluate that macro in the rootfs and use the value to get the correct rpmdb path.

**Comment by schaefi** [comment]
I knew this change will have some negative side effect which we overlook :(

**Comment by schaefi** [comment]
Thanks for the feedback

@davidcassany: Could you have a look at it again ? Thanks much
