### ISSUE TITLE
initrd_system attribute is only available for the following image types: oem

### ISSUE THREAD

**Issue by toabctl** [SUSE/kiwi#552]
## Problem description
```initrd_system=dracut``` does no longer work for ```vmx``` image types. This was working in previous versions and is also documented as a working solution (see https://suse.github.io/kiwi/overview/workflow.html#customizing-the-boot-process , last words in the "important" box)

## Expected behaviour
```initrd_system=dracut``` works with ```vmx```

## Steps to reproduce the behaviour
Look at any image in https://build.suse.de/project/show/home:tbechtold:Images

**Comment by toabctl** [comment]
Hm. Looks like ```dracut``` is now the default for ```vmx``` image types?

**Comment by schaefi** [comment]
yes iso and vmx switched to dracut. We did not auto convert the schema because the semantic is the same but the concept has changed here. So vmxboot and isoboot description has also been deleted from kiwi and the code for this is now provided as dracut module packages if needed:

* standard disk boot is part of dracut upsream
* kiwi live iso boot as we want it is provided by dracut-kiwi-live

There are also runtime checks which tells if one ore more of the dracut module packages are missing in your package list depending on the selected type and feature

I'm also working on moving oemboot and netboot into dracut but there we will allow both, dracut boot and custom kiwi boot code for a transition period

For vmx it means just delete the initrd_system attribute from your type definition

Hope that helps

**Comment by schaefi** [comment]
Overall goal is to get rid of kiwi's custom boot code which needs to be maintained per distro and move that into a generic code base as dracut module and benefit from all the code dracut already has.
