### ISSUE TITLE
Different root overlays for boot/system images

### ISSUE THREAD

**Issue by Jellyfrog** [SUSE/kiwi#553]
## Problem description
We need to use two different "root overlays", one for the *boot*-image and one for the *system*-image.
Using `<archive>` is not possible since there is only `bootinclude` and no `systeminclude`.
Using the root tarball or folder is not possible since it uses the same name `root`.

Only option left is to pack two rpms and use `<packages type="delete">` to remove the boot rpm in the system image, however this adds problem with conflicts when overwriting files, for example `/etc/issue`

Also, we use the standard `boot="oemboot/suse-SLES12"`, it feels very unnecessary to pack our own description just for adding this.

## Expected behaviour
Providing a `systeminclude` attribute on `<archive>`
or
Use different names for the `root'-folder for boot / system images

## OS and Software information
+ KIWI version: 9.11.24
+ Operating system: SLES12-SP3
+ OBS version: 2.7

**Comment by davidcassany** [comment]
@Jellyfrog I have been thinking a little about that I think that rather than allow a _root-overlay_ for system image and another one for the boot image (which would be strange since the boot image already has its own _root-overlay_) as we commented on IRC, I'd say there are different alternatives to handle that without having to add an extra boot specific _root-overlay_ management logic.

The first that comes to my mind is to add a new attribute to `<package>` or `<archive>` tag, probably "bootonly=<boolean>". This attribute would indicate that the mentioned package or archive needs to be installed expanded only into the boot image, but not into the system root. This way one could have a boot-root.tar.gz archive included into OBS package as another source file.

Another option that came to my mind in order to facilitate the usage of custom boot images within the OBS scope is to allow the `boot` attribute value to be evaluated also inside the description directory. Imagine that kiwi with a `boot="oemboot/suse-leap42.3"` would at first look for that boot description inside the current project folder, and if it does not find it, then it would look for the default path in `/usr/share/kiwi/`. This way one could easily copy a default boot image, include it as part of the project and hack it without the risk of messing with package provided files. This could be done inside OBS as currently it supports folders as sources (as we are doing with the testing images).

thoughts?

**Comment by Jellyfrog** [comment]
@david

**Comment by Jellyfrog** [comment]
Ops. Miss click on phone. 

@davidcassany my idea with `systeminclude` is the same as your `bootonly`, only named differently, I matched the `bootinclude` attribute.
I think that attribute makes a lot of sense regardless of this specific issue

**Comment by schaefi** [comment]
Here are my two cents on this topic:

1. You should always have in mind that custom boot images as we create it today will go away with our effort to move that code into dracut modules. Thus I don't plan to add more features to the custom boot image coding. I would say that eliminates that we add a bootonly attribute because it would be pointless when dracut is used. We already have to deal with the problem that bootinclude is pointless  if dracut is used as initrd system which is the default for vmx and iso types today. Thus I'm not a fan of adding more of these.

2. To me it looks like you are using a highly customized initrd already with many hooks and now also additional code you want to embed by either an archive or package. We allow custom initrd's via the boot= attribute as David already mentioned. If there is so much to add that it can't be provided as hook scripts or that it is a problem if the package exists in system and boot image, I think the point is reached where it makes sense to maintain your own initrd as it would also be very different from what we provide. Or is this wrong ? If I'm wrong I'd like to understand what software this is which needs to be available in the boot image only and can't be easily part of the system as well or can't be uninstalled with a call like `zypper remove --clean-deps your-pack` in config.sh if adding it to the delete section is not enough as well.

3. For pointing a boot description to the base directory of the system description we had the following uri type in the past: `boot="this://my-bootdesc"`. However we did not yet port the this:// uri style to the next generation kiwi code. I would be open to add that uri style so you could maintain your custom initrd as part of the system description as David mentioned

Thoughts ?

**Comment by Jellyfrog** [comment]
Actually our initrd is fairly straight forward with only 2 hooks (even if a lot happens inside the hooks) so not maintaining another kiwi description would be preferable. 
Packing the overlays as rpms bring problems with conflicts, like for example `/etc/issue`.
However if this all changes with the new dracut modules, maybe there is no point to continue on this and I'll just solve it some other way instead

**Comment by schaefi** [comment]
with dracut there is no extra system build from which the initrd is created. Thus there is no need to maintain two root tree's which in the end makes all data in kiwi/boot/arch obsolete. The hook system of dracut is based on systemd services, so you should be done by adding your hooks as dracut module

But all this is work in progress we are not done. As long as we are not done you will be able to use the old way which keeps your current setup working

I don't understand what you mean with "Packing the overlays as rpms" brings problems...

**Comment by schaefi** [comment]
Per discussion on irc I think this one can be closed
