### ISSUE TITLE
"delete" section before config.sh, but why? (kiwi-ng only)

### ISSUE THREAD

**Issue by Phazeus** [SUSE/kiwi#566]
In legacy KIWI the "delete" section with packages counting to delete was proceed after "config.sh" script calling.  I have some packages I not needed after building, but I need them for compiling some stuff in "config.sh" script (some .devel packages). After that this packages goes to deletion.
In KIWI-NG they deleting BEFORE calling config.sh and compilation fails. I has remove "delete" section in config.xml and just delete unneeded packages manually in config.sh script.

So, may be more logically do "delete" section after calling "config.sh" script?

Thanks.

**Comment by schaefi** [comment]
Actually this was a mistake in the legacy kiwi version

Before config.sh is called kiwi knows the context of the root system and has the ability to install and delete packages. After config.sh the environment and everything else could be different and deleting a package could be no longer possible because e.g the rpm database was changed via config.sh

As you can do everything in config.sh we want this to be the last action of the prepare step before
the cleanup.

As it seems you need those packages for a compile job in config.sh, they form a dependency to
config.sh and not to the image. So the most clean way would be if you install and delete those as
part of your config.sh scripting and keep kiwi free of those packages.

Thanks
