### ISSUE TITLE
Support for iso-scan to live overlay module

### ISSUE THREAD

**Issue by cyberorg** [SUSE/kiwi#574]
## Problem description
Earlier openSUSE live were able to boot from iso images, after the change to dracut we are unable to do that, this is a regression.

## Expected behaviour
As dracut already supports iso-scan, adding support to overlay module will allow feature parity in this regards.

https://github.com/haraldh/dracut/blob/master/dracut.cmdline.7.asc#iso-scanfilename 
Appending iso-scan/filename=/$isoname root=LABEL=$isolabel should get it booting.

Having something equal to kiwi_cowdevice=/dev/disk/by-uuid/$stickuuid kiwi_cowsystem=/boot/cowfile would also be nice.

Also see: https://github.com/SUSE/kiwi/issues/521

**Comment by davidcassany** [comment]
@cyberorg I was lookig at #521 and finally I found myself investigating this issue, since it looks like it might be an interesting pre step for #521.

Are you aware that live images can be done using two different dracut modules (kiwi-live or dmsquash-live, the latter is the current upstream dracut live module)?

Up to now what I found is that iso-scan is part of the dmsquash-live dracut module, which kiwi already supports (`flags="dmsquash"` on type section). I managed to boot an iso image from grub2 using the example form the dracut [man page](https://github.com/haraldh/dracut/blob/master/dracut.cmdline.7.asc#iso-scanfilename) you shared. The label of KIWI live CD's is `CDROM`.

According to that I would say this issue is already covered by KIWI when using the dracut livecd module. Adding support for iso-scan to kiwi-live module I don't think is something we want, having our own module that is coupled with the code of some other upstream module doesn't sound like a good idea to me (assuming that iso-scan scripts could used in kiwi-live as is or with few adaptations), and also duplicating code and features I am not sure it a good idea also.

Is there any specific need or use case in which `kiwi-live` is required in favor or `dmsquash-live` and also bootable isos are needed?

If no clear use case I'd say we are fine assuming it is possible by using `flags="dmsquash"` in your type section.

Any thoughts?

Oh, a side note just in case, I noticed that booting from the iso does not work is the host holding the image is using btrfs subvolumes (but I assume this an unrelated battle). Lost some hours yesterday because of that.

**Comment by cyberorg** [comment]
> Is there any specific need or use case in which kiwi-live is required in favor or dmsquash-live and also bootable isos are needed?

Official openSUSE iso uses kiwi-live module, so the ability to boot it from iso is lost, having this feature available in both module would allow end users to use the isos in same manner regardless of the kiwi module used to create them across all the distributions that support iso-scan to boot from iso images.

The case for being able to boot from iso is the same for which dracut and earlier kiwi initrd had that feature i.e,

* Being able to boot from any partition(vfat/ext2/3 etc.) from usb stick or local hdd
* Preserve pre-existing data in partition when creating bootable disk
* Have complete iso image in boot stick so it can be copied around for sharing from the same disk
* Create multiboot disk with many distribution isos for testing and sharing, used a lot by teachers, students and sysadmins as recovery disks for various distributions they support.

I am sure lot more reasons can be found. The above were just my reasons for creating https://github.com/cyberorg/live-fat-stick

**Comment by davidcassany** [comment]
> Official openSUSE iso uses kiwi-live module, so the ability to boot it from iso is lost, having this feature available in both module would allow end users to use the isos in same manner regardless of the kiwi module used to create them across all the distributions that support iso-scan to boot from iso images.

Oh sure, you are right here, if official images lose this feature this is bad, I agree.

About the use cases for having a bootable iso they are clear to me, I was just wondering if using dmsquash was sufficient for that purpose, but probably the above reason is just relevant enough. Ok, I'll have a close look to dmsquash scripts and check how the idea can be applied to kiwi-live.

Thanks for you feedback

**Comment by schaefi** [comment]
The move from isofrom to what dracut upstream supports with iso-scan affects the way the grub loopback mounted iso is found by the initrd code. The setup of persistence is not directly related to it and is part of the image description. As I don't know who created/maintains openSUSE-Tumbleweed-KDE-Live I can only guess that this description does not setup live persistence and the default is temporary persistence

You should be able to test this if you modify the live-grub-stick generated grub2 config and pass the following value to the kernel cmdline:

* rd.live.overlay.persistent

If that does not help please also pass ``rd.kiwi.debug``` and send along the log file in ```/run/initramfs/log/boot.kiwi``` 

Thanks

**Comment by wandersfalsin** [comment]
I did the test, I put the parameter and the persistence did not mount. I noticed that the pendrive partition mounted read-only. I tested with fat32 and ext4 and the result was the same.

[boot.kiwi.txt](https://github.com/SUSE/kiwi/files/2511072/boot.kiwi.txt)
