### ISSUE TITLE
Allow strings (eg. -beta) as part of the image version

### ISSUE THREAD

**Issue by bgeuken** [SUSE/kiwi#598]
## Problem description
We would like to have an -alpha, -beta, ... suffix as part of our image versioning. So we adjusted the versioning to ` <version>2.9.0-alpha</version> `. This works for all the appliances we are building (vmx, hybrid iso and qcow), but docker.

```
[  182s] Jan-30 07:12:56 <3> : Invalid version format: 2.9.0-alpha
[  182s] Jan-30 07:12:56 <3> : Expected 'Major.Minor.Release'Jan-30 07:12:56 <3> : KIWI exited with error(s)
```

The Kiwi documentation states "The image version must be a three-part **version number** of the format: Major.Minor.Release." So I assume this is expected and I would like to request feature to also allow strings in the version, or at least as part of the last *Release* digit.

## OS and Software information
+ KIWI version: 7.04.8-5.1
+ Operating system: openSUSE Leap 42.3
+ OBS version: 2.8.51.git20180123T125721.7a2e199af (build.opensuse.org)

**Comment by schaefi** [comment]
You are right the version schema is intentional a three part version number and we rely on this to be valid at several places in the documentation as well as in the deployment code. To be honest I don't want to touch this because we check this condition in the schema and expect the format to be consistent after the schema validation has passed. This means there are no further validation checks of the version format in the code and this version information is handed over through the complete pipeline up to the initrd code.

If we allow other strings and open this to be numbers and a mix of "something" things starts to become more complex as they should be and that opens a can of worms I'm not willing to open ;)

However you have the opportunity to add the information you need. Actually if something is alpha or beta is not necessarily a version information by the definition of major.minor.release it imho states more a quality or mature level. Thus you should be fine with the following definition:

```xml

<image ... name="your-image-alpha" displayname="your-image">
     <preferences>
         <version>1.2.3</version>
     </preferences>
</image>
```

The name information is part of the later image file, which means your image file has it. the displayname information can be used to display a different name in the boot menu of the image, just in case you don't want to publish the alpha/beta something information when you boot the image

That way you can embed additional meta information and keep the version format as it is

If this does not match your use case feel free to re-open

Thanks
