### ISSUE TITLE
SLE15 vagrant image build

### ISSUE THREAD

**Issue by denisok** [SUSE/kiwi#604]
## Problem description
`<type image="vmx" filesystem="ext4" boot="vmxboot/suse-SLES15" format="vagrant" ...`
suse-SLES15 is unresolvable .

> image="vmx"
> Creation of a virtual disk system is enabled with the vmx value of the image attribute. Set the filesystem of the virtual disk with the filesystem attribute and select the appropriate boot image by setting boot="vmxboot/suse-*"

## Expected behaviour

Creation of SLE15 box.

## Steps to reproduce the behavior
https://build.suse.de/package/show/home:dkondratenko:images:vagrant/sle15

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version: 

build on internal IBS.

## Question

Is there a plan to add SLE15 to supported images for vmxboot ? and what is the timeline for it?

Is that  boot="vmxboot/suse-*" parameter is required? If I remove it - it builds OK, looks like...

**Comment by davidcassany** [comment]
@denisok, in current kiwi versions the boot descriptions for vmx are completely dropped, meaning that the attribute `boot="path/to/boot/description"` is incompatible with `image="vmx"`. So to build vmx images now is not needed anymore to include a boot description.

The difference is that the vmx image types are fully using dracut in order to create the initrd and thus there is no longer need to define a custom one.

> Is there a plan to add SLE15 to supported images for vmxboot ? and what is the timeline for it?

No, it won't be supported. The vmxboot descriptions are dropped in current KIWI.

> Is that boot="vmxboot/suse-*" parameter is required? If I remove it - it builds OK, looks like...

No, it is not required at all, it is not even permitted. It should have thrown you a message like:

```
boot attribute is only available for the following image types: oem pxe
```

**Comment by davidcassany** [comment]
Closing the issue, please feel free to ask for further explanations if needed and also feel free to reopen the issue if this is causing you some further inconvenient.

**Comment by denisok** [comment]
@davidcassany , cool - tnx. Is there new document describing that or old document will be updated.
I am reading this one:
https://doc.opensuse.org/projects/kiwi/doc/

**Comment by davidcassany** [comment]
@denisok oh sorry, I should have pointed that out in the first place. The docs you are looking at are for the former kiwi version (kiwi v7.x). Current kiwi (python-kiwi v9.x) and future releases are documented here: 

https://suse.github.io/kiwi

Probably there should be some clear advise in the old document that this is only valid for kiwi versions up to v7.x.

**Comment by denisok** [comment]
@davidcassany tnx!
