### ISSUE TITLE
Adding a preference type doing nothing

### ISSUE THREAD

**Issue by jezze** [SUSE/kiwi#620]
Hi!

This is a feature request. I tried to send this to the google group but it did not seem to exist anymore.

Anyway, right now I am using tbz as my preferences type but what I really want to do is to archive it together myself.

Is there an option to do no archiving after all of the packages have been installed into the image-root?

If not, can I suggest to add a preferences type called "none", "custom" or something like that?

If you don't like that idea - can suggest to add compression="no" to the tbz type so that it does no xz compression and just archives the files using normal tar?

Thanks!

**Comment by schaefi** [comment]
> This is a feature request. I tried to send this to the google group but it did not seem to exist anymore.

it does and is active: https://groups.google.com/forum/#!forum/kiwi-images
Do you reference another group ?

> Is there an option to do no archiving after all of the packages have been installed into the image-root?

no but I think what you are aiming for can be easily done by just calling kiwi's prepare step instead of build.

```
kiwi-ng system prepare --description <your-image-descr-path> --root <your-image-root>
```

If that's done you can apply whatever archiving method you prefer on the created system root tree

**Comment by jezze** [comment]
You are totally right, this was exactly what I was after. Thanks for the quick reply.

// Jens
