### ISSUE TITLE
Allow deletion of packages which aren't needed in the root fs anymore

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#625]
Currently, it's not possible to remove grub/plymouth/dracut/genisoimage/etc. packages as they are used by kiwi later on.

It should be possible to delete those (and also its dependencies) by generating the needed files before processing the `delete` sections.

**Comment by schaefi** [comment]
Sorry what ?

**Comment by Vogtinator** [comment]
Currently you can't put `dracut` into the `<packages type="delete"/>` section as it is needed by kiwi to generate the initrd put on the iso.

The result is that you have a full dracut installation + dependencies inside the squashfs, which just wastes space.

**Comment by schaefi** [comment]
Ah you are talking about live iso images and the contents of the compressed rootfs.img

**Comment by schaefi** [comment]
I'm not sure if we can do much here. The initrd creation tools basically belongs to the system and our live iso images are hybrid meaning they can be used also in a persistent storage area e.g on stick which would allow to update the kernel get security fixes etc, etc and that would cause recalling dracut on e.g kernel update. What you are suggesting is to provide an inconsistent system which would work under certain circumstances for the benefit of a couple bytes

I think there are other parts of the system which are not core tools which have more potential to save space

I'll keep this open for a discussion

@davidcassany would be great to know what you think about it

Thanks

**Comment by davidcassany** [comment]
Well I think that some initial investigation would be required here, I am wondering how other livecd producers are handling this situation. 

I think that should be noted that the deletion of dracut and similar packages cause dependency breaks, for example dracut is an indirect systemd dependency and I doubt you want to run a livecd with a potentially broken systemd or other sensitive tools.

Also, targeting the use case is relevant for this feature, as @schaefi said we can produce hybrid images which can be persistent, in that case having broken dependencies I think is not a good option, as the user could potentially install stuff or find issues trying to do so.

I'd say we should try to (i) narrow the scenario,  (ii) see what others do and (iii) make sure there is a relevant gain with such a feature. I don't really like the idea of letting the user do inconsistent or incoherent builds (like wild deletion of packages right before compressing the live image).

**Comment by Vogtinator** [comment]
> Also, targeting the use case is relevant for this feature, as @schaefi said we can produce hybrid images which can be persistent, in that case having broken dependencies I think is not a good option, as the user could potentially install stuff or find issues trying to do so.

Maybe a new section which doesn't do `rpm -e --nodeps` but rather `zypper rm` would be appropriate?

**Comment by davidcassany** [comment]
> Maybe a new section which doesn't do rpm -e --nodeps but rather zypper rm would be appropriate?

My biggest concern here is if it is really possible to have a relevant reduction by only using `zypper rm` or `rpm -e --nodeps` of certain packages without limiting image functionality. And also how to configure it or manipulate it.

**Comment by schaefi** [comment]
The reason why the packages in the ```delete``` section are force deleted is because this feature is used to delete packages which formerly gets pulled in by dependencies. Thus calling ```zypper rm``` in non interactive style does not what users want when they make use of the delete section

**Comment by schaefi** [comment]
personally I would be mostly interested how much space in the compressed image you really save when dracut is not installed. If I see a really relevant number it makes sense to continue the discussion. 

* dracut's install size is: 1141567 bytes
   in the squashfs this will be compressed and dracut is text only data, thus very good compression

* dracut's dependency list is

  /bin/bash
  /usr/bin/get_kernel_version
  /usr/bin/perl
  /usr/bin/pkg-config
  binutils
  coreutils
  cpio
  file
  findutils
  grep
  hardlink
  libc
  modutils
  pigz
  systemd
  udev
  sed
  util-linux
  xz

  Apart from perl I don't see a relevant space consumer and I bed you will not be able to get rid of perl completely and still have a running Linux as you want it with the live CD

**Comment by schaefi** [comment]
After all and with years of experience in trying to reduce the size of an os by hacks like this, deleting packages files and stuff which gets pulled in by dependency I can assure you the only good way to achieve this is by the packages itself. Keep the packages small, keep their dependencies small and this for all packages of the distro and you gain the ability to build small and consistent os images. Everything else just sucks at some point

That's why I really need very convincing arguments to put effort in pro active deletion of data and with kiwi we already provide an intrusive way to just delete packages which already allows to create completely broken images. I'm not too motivated to expand the capabilities :)

**Comment by Vogtinator** [comment]
> personally I would be mostly interested how much space in the compressed image you really save when dracut is not installed. If I see a really relevant number it makes sense to continue the discussion.

I can save around ~50MiB by removing stuff only needed by kiwi during build (e.g. grub and plymouth themes). I'm not sure how much that amounts to in the final iso as I was never able to build such an image successfully.
For a live cd that's actually a lot of space.

> After all and with years of experience in trying to reduce the size of an os by hacks like this, deleting packages files and stuff which gets pulled in by dependency I can assure you the only good way to achieve this is by the packages itself. Keep the packages small, keep their dependencies small and this for all packages of the distro and you gain the ability to build small and consistent os images. Everything else just sucks at some point

This is actually not about breaking dependencies at all, just providing a way to remove unnecessary packages and their deps completely and cleanly.

There's no way around kiwi needing the grub2 theme during build, but after building it is surely not necessary anymore.

**Comment by Vogtinator** [comment]
What might make sense IMO is to have `images.sh` (or was it `isopatch.sh`?) running while the rootfs is not yet compressed. That way a script can do whatever it wants with both the iso and the rootfs contents.

**Comment by schaefi** [comment]
> I can save around ~50MiB by removing stuff only needed by kiwi during build 

wait wait wait we are not talking about stuff needed by kiwi.

The packages you mentioned are core part of the suse distribution. You have them with any installation. This has nothing to do with kiwi, it's a pure os specific scenario. The fact that a dracut call embeds e.g plymouth themes from an of course required to be installed theme collection of theme data has no relation to the image builder. You need an initrd to boot and that thing is created by a tool and that tool needs data to process a correct result.

There is nothing holding you back to write a cleanup service which allows to delete data you consider not needed anymore but it's not the responsibility of the image builder to do that.

If this would exist we would be more than happy to make use of it. The unconditional way to just delete stuff from the system wherever you and tomorrow some other guys think it fits in will not be something we accept. I learned the lesson from the kiwi v7 project and one result is that the image builder has not the responsibility to work around distribution design flaws or hack around the tooling

So sorry your issue here is not related to kiwi. if we can make your live simpler we are always open to help out but not for the price to make our live more complicated.

**Comment by schaefi** [comment]
* config.sh: at the end of the system root tree creation
* images.sh: at the beginning of the image creation from the root tree

> What might make sense IMO is to have images.sh (or was it isopatch.sh?) running while the rootfs is 
> not yet compressed.

surely not because there are not only live iso images in this world. Why not write a ```live-system-cleaner``` package it and give us the opportunity to call it as part of the live iso image creation process.
That's clear, explicit and use case driven and not:

>  That way a script can do whatever it wants with both the iso and the rootfs contents.

never ever

**Comment by Vogtinator** [comment]
I think you misunderstand.

> wait wait wait we are not talking about stuff needed by kiwi.

KIWI needs dracut to be part of the OS image, not the OS image itself.

> There is nothing holding you back to write a cleanup service which allows to delete data you consider not needed anymore but it's not the responsibility of the image builder to do that.

It has no effect as it is the data on the medium itself that needs to be deleted.

> Why not write a live-system-cleaner. Package it and give us the opportunity to call it as part of the live iso image creation process.

Breaks the kiwi build.

Let me give you a very concrete example based on dracut.

This line in kiwi is literally the only reason dracut is needed:

`[ 2348s] [ DEBUG   ]: 13:53:30 | EXEC: [chroot /usr/src/packages/KIWI-iso/build/image-root dracut --force --no-hostonly --no-hostonly-cmdline --xz openSUSE-Leap-15.0-GNOME-Live.x86_64-2.8.0.initrd.xz 4.12.14-lp150.4-default]`

This is executed *after* the squashfs image is finalized, which means the rootfs image can't be changed anymore. So it's impossible to get rid of dracut at all.

**Comment by schaefi** [comment]
> This is executed after the squashfs image is finalized, which means the rootfs image
> can't be changed anymore.

This is not correct. A live iso is a hybrid root filesystem overlayed by overlayfs. The overlayfs mount makes the system a fully writable rootfs. The write part either lives in ram or on a persistent storage.

The live system is the exact same suse system as if you would have installed a normal suse system.
Any installation of a normal suse system has dracut and its dependencies. The fact that dracut is called as part of an image building process is because a suse linux system needs an initrd. In a normal install process this is done as part of the yast process

you can at any point in time update the kernel of your live system. update of the kernel causes a recall of dracut because the kernel package triggers this. If the required components are not existing on the system this post script would fail... your system gets inconsistent.

yes it doesn't make sense to update the kernel on a live system overlayed in ram because on boot the change will be lost, but put the exact same iso on a usb stick and you gain persistency and a fully functional os

I think you don't get my point here. Try to look in a more global space

> This line in a kiwi build log is literally the only reason dracut is needed:

This wrong, a hostonly initrd is created not only by kiwi, any package update which influences the contents of the initrd triggers a dracut call. I can just repeat myself this is not a kiwi thing

again:

Why not write a live-system-cleaner. Package it and give us the opportunity to call it as part of the live iso image creation process.

> Breaks the kiwi build.

why should that break the build. That's just more work but a better and clean solution unless I completely misunderstand what you want to achieve. If such a tool would exist we would call it right before the compression. Of course we would also change the point in the processing when dracut is called to make sure all it needs is still there

It feels like you think a ```zypper -u dracut``` is the final and simple solution to your problem.
But that's too short thinking and only really only might solve your space issue for your live iso use case.
It also opens a gate of other problems which we don't want

**Comment by schaefi** [comment]
rpm -q --requires kernel-default

* mkinitrd >= 2.7.1

which means dracut, as this is only an alias name. So deleting dracut is really not a good idea

**Comment by davidcassany** [comment]
Just to add my 2 cents, I agree with @schaefi that including into kiwi another hook to include in the build some sort of script to give absolute freedom to the user hack around in yet another step during the build is definitely not what we are after. We should minimize those as much as possible and this is what we are after. That's why I noted the configuration, manipulation or user interaction as one of my biggest concerns here.

Also, I think that looking how other live images out there handle this situation matters. This is relevant because we aim to support also other distros besides suse or opensuse; and because what we could consider is an improvement on our livecd build receipt in contrast to some specific hack around some specific distro version.

Finally, if reviewing the live build procedure to make it smarter (by using some new tools to clean or by making the builder not relay on some tools in the rootfs) is considered, we need to make sure we are capable to have some valuable gain, otherwise we will just be making our code more complex and error prone in some sensitive parts.

**Comment by Vogtinator** [comment]
>  That's just more work but a better and clean solution unless I completely misunderstand what you want to achieve

The end goal is to make the .iso smaller, if just by a handful of MiB.

> Finally, if reviewing the live build procedure to make it smarter (by using some new tools to clean or by making the builder not relay on some tools in the rootfs) is considered, we need to make sure we are capable to have some valuable gain, otherwise we will just be making our code more complex and error prone in some sensitive parts.

I would give it a try, but currently that's not easily possible. Maybe with `zypper --root` and manually calling squashfs...

**Comment by Vogtinator** [comment]
There is another use-case for this - some packages aren't needed after installation of other packages as they are only used during `%postin` and/or similar sections. `shadow` and `fillup` for example.

Calling `zypper rm -u fillup shadow` in `config.sh` would work, but having that in the .xml itself is cleaner.

**Comment by davidcassany** [comment]
> Calling zypper rm -u fillup shadow in config.sh would work, but having that in the .xml itself is cleaner.

In fact we have the code almost ready to do that. The `packages` section of `type=delete` results in a call of `PackageManager.process_delete_requests(self, force=False)` which in turn results in:

```bash
rpm -e <package>
```
when `force=True`. But if `force=False` then it results in:

```bash
zypper rm -u <package>
```
I think that currently we have no way to control the `force` flag. I'll look at it and run some tests, probably there is something I am missing.

**Comment by davidcassany** [comment]
@schaefi, I found that currently our `packages` section for `type=delete` always uses the `force=True` to remove the packages listed in the description file, but it uses the `force=False` for the packages listed using the `--delete-package` command line flag. Is this difference done in purpose? Or it is just kind of a leftover?

Also, just nitpicking, it doesn't hurt at all, but the `package_requests` variable usage in `kiwi/tasks/system_build.py` (lines 176~196) looks redundant :)

**Comment by schaefi** [comment]
> Is this difference done in purpose?

yes on purpose. The behavior is based on the use case for the two settings. When people use the
type=delete section their reasons are because those packages gets pulled in by dependencies and they want to get rid of them. If we don't force delete those the request will fail. That's because if those packages are unwanted you could just prevent to list them in the type=image section. Packages which gets pulled in as recommended could be deleted without the force flag set, that's true but also covered by the force flag set to true.

The other call with --delete-package might be the consequence of a former --add-package and in this situation we let users only do what the package manager thinks can be done

> looks redundant :

On a short look I agree, that could be probably written with less code

**Comment by davidcassany** [comment]
Ok I see, thanks @schaefi.

Then about
> Calling zypper rm -u fillup shadow in config.sh would work, but having that in the .xml itself is cleaner.

Then I think calling zypper in the config.sh is the way to go in this case. I don't think the complexity of adding an extra option in .xml in order to run non forced removals using zypper is worth. I guess scripting in config.sh using `zypper packages --unneeded` and `zypper packages --orphaned` results to remove unneeded packages should be sufficient. And if there is still some gap between `zypper package --unneeded` and packages only required in `%postin` I'd say this is way too specific to be generalized or handled somehow in KIWI, it looks more like a package manager optimization.

**Comment by Vogtinator** [comment]
I'd very much like to see `<packages type='delete'><package force='false'>foo</package>...` or something similar.

**Comment by schaefi** [comment]
I would be ok with a new type class to delete with clean dependencies, e.g

```xml
<packages type="delete_clean_dependencies">
    <!--- add packages which can be deleted conflict free here 
            be aware that deletion happens with clean dependencies which might affect
            the deletion of other packages not explicitly listed. Also note your build will fail
            if the deletion request can't be processed for whatever reason by the used
            package manager -->
    <package name="vim"/>
</packages>
```

Thoughts ?

**Comment by davidcassany** [comment]
I am fine with it and probably apply the deletion after the config.sh (delete packages are delete before that) as this could be a clean way to delete any package that is only needed for some config.sh procedure (for example adding repositories with yast or jeos-firstboot tools).

**Comment by schaefi** [comment]
yes would be ok for me too

**Comment by Vogtinator** [comment]
Sounds perfect to me.

**Comment by Conan-Kudo** [comment]
@schaefi I'm not okay with this.

I didn't realize `delete` used `rpm --nodeps -e` to erase packages. That's not smart at all. In almost every circumstance I can think of, people generally expect it to be removed correctly by the depsolving package manager.

This should absolutely be the default and expected behavior, as it's the one of least surprise. If you _want_ to have a way to do `rpm --nodeps -e`, then make an attribute for `delete` that does that, but please don't make a new section for it, because it's stupid to preserve "compatibility" with horrible behavior.
