### ISSUE TITLE
Use xz for squashfs compression

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#63]
## Problem description

The default compression in mksquashfs is gzip. The other compression
(xz) gives a size reduction of almost 10%.

## Actual behaviour

gzip compression by default, faster in filesystem creation but larger result than with xz

## Solution suggestion

call mksquashfs with -comp xz

**Comment by schaefi** [comment]
Think about a configuration attribute

**Comment by md-work** [comment]
I'd also like to see a configuration attribute. I build a lot of test images and I don't care much about the size of those, because I delete them after a few minutes of testing. The image creation speed is much more important for me, so I'd like to use gzip for those.

Nevertheless xz is definitely the right thing for images being published on a website.
