### ISSUE TITLE
not able to build LVM image

### ISSUE THREAD

**Issue by yeoldegrove** [SUSE/kiwi#631]
## Problem description
I am not able to build any LVM enabled oem image with kiwi.
My syntax works with kiwi7, but not with latest kiwi-ng.

build log:
```
[  230s] [ INFO    ]: 09:19:47 | Creating raw disk image /usr/src/packages/KIWI-oem/SLES_15SP0_xen.x86_64-0.0.1.raw
[  230s] [ DEBUG   ]: 09:19:47 | EXEC: [qemu-img create /usr/src/packages/KIWI-oem/SLES_15SP0_xen.x86_64-0.0.1.raw 2782M]
[  230s] [ DEBUG   ]: 09:19:47 | EXEC: [losetup -f --show /usr/src/packages/KIWI-oem/SLES_15SP0_xen.x86_64-0.0.1.raw]
[  230s] [ DEBUG   ]: 09:19:47 | Initialize gpt disk
[  230s] [ DEBUG   ]: 09:19:47 | EXEC: [sgdisk --zap-all /dev/loop0]
[  231s] [ INFO    ]: 09:19:48 | --> creating EFI CSM(legacy bios) partition
[  231s] [ DEBUG   ]: 09:19:48 | EXEC: [sgdisk -n 1:0:+2M -c 1:p.legacy /dev/loop0]
[  232s] [ DEBUG   ]: 09:19:49 | EXEC: [sgdisk -t 1:EF02 /dev/loop0]
[  233s] [ INFO    ]: 09:19:50 | --> creating EFI partition
[  233s] [ DEBUG   ]: 09:19:50 | EXEC: [sgdisk -n 2:0:+20M -c 2:p.UEFI /dev/loop0]
[  234s] [ DEBUG   ]: 09:19:51 | EXEC: [sgdisk -t 2:EF00 /dev/loop0]
[  235s] [ INFO    ]: 09:19:52 | --> creating LVM root partition
[  235s] [ DEBUG   ]: 09:19:52 | EXEC: [sgdisk -n 3:0:0 -c 3:p.lxlvm /dev/loop0]
[  236s] [ DEBUG   ]: 09:19:53 | EXEC: [sgdisk -t 3:8E00 /dev/loop0]
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [kpartx -s -a /dev/loop0]
[  237s] [ INFO    ]: 09:19:55 | Creating EFI(fat16) filesystem on /dev/mapper/loop0p2
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [mkdosfs -F16 -I -n EFI /dev/mapper/loop0p2]
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [vgs --noheadings -o vg_name]
[  237s] [ INFO    ]: 09:19:55 | Creating volume group local
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [vgremove --force local]
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [pvcreate /dev/mapper/loop0p3]
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [vgcreate local /dev/mapper/loop0p3]
[  237s] [ INFO    ]: 09:19:55 | Creating volumes(ext4)
[  237s] [ DEBUG   ]: 09:19:55 | EXEC: [du -s --apparent-size --block-size 1 /usr/src/packages/KIWI-oem/build/image-root]
[  238s] [ DEBUG   ]: 09:19:55 | EXEC: [bash -c find /usr/src/packages/KIWI-oem/build/image-root | wc -l]
[  238s] [ INFO    ]: 09:19:55 | --> volume LVRoot with 2680 MB
[  238s] [ DEBUG   ]: 09:19:55 | EXEC: [lvcreate -L 2680 -n LVRoot local]
[  238s] [ DEBUG   ]: 09:19:55 | EXEC: Failed with stderr:   WARNING: Failed to connect to lvmetad. Falling back to device scanning.
[  238s]   /dev/local/LVRoot: not found: device not cleared
[  238s]   Aborting. Failed to wipe start of new LV.
[  238s] , stdout: (no output on stdout)
[  238s] [ ERROR   ]: 09:19:55 | KiwiCommandError: lvcreate: stderr:   WARNING: Failed to connect to lvmetad. Falling back to device scanning.
[  238s]   /dev/local/LVRoot: not found: device not cleared
[  238s]   Aborting. Failed to wipe start of new LV.
[  238s] , stdout: (no output on stdout)
```

Full example:
https://build.opensuse.org/package/show/home:waldt:branches:SUSE:Templates:Images:SLE-15/kiwi-SLES15-xen

Full logs:
https://build.opensuse.org/build/home:waldt:branches:SUSE:Templates:Images:SLE-15/images/x86_64/kiwi-SLES15-xen/_log

## Expected behaviour
With kiwi7 I can build an image with the following syntax in OBS:
```
      <systemdisk name='local'>
          <volume name='@root' size='2048M'/>
          <volume name='var' mountpoint='/var' size='8192M'/>
          <volume name='tmp' mountpoint='/tmp' size='2048M'/>
      </systemdisk>

```

## Steps to reproduce the behaviour
Try to use LVM in kiwi oem image build.

## OS and Software information
+ KIWI version: 
python3-kiwi-9.12.6-1.2
+ Operating system: 
SLES 15 from OBS GA sources
+ OBS version: 
build.opensuse.org

**Comment by schaefi** [comment]
This doesn't look like a kiwi error. The problem is the device path expected to be created by lvcreate does not exist. This could have several reasons, e.g

* no udev running on your build host
* or your buildhost is an unprivileged container
* or your host system uses btrfs and the volume conflicts with a subvolume
* or your build host has the lvmetad running
* or your build host itself is lvm based
* or your build host has still open lvm maps from earlier attempts and is in an inconsistent state

You can test this as follows:

```
qemu-img create foo 20g
losetup -f --show foo

==> assume /dev/loop0 is the return value from losetup

fdisk /dev/loop0

==> create one lvm partition
       n p . . t 1 8e

kpartx -s -a /dev/loop0
pvcreate /dev/mapper/loop0p1
vgcreate local /dev/mapper/loop0p1
lvcreate -L 200 -n LVRoot local

==> get the same error ? if yes check by the list above what could have caused it
```

**Comment by schaefi** [comment]
Oh and I see you build in obs, then it's clear. The obs workers do not support creating lvm devices
You could report this to the obs team like I did some time ago. A possible solution could be to use
kernel-default instead of kernel-obs-build for the obs worker (untested though). I think this can be
setup in the prjconf

**Comment by yeoldegrove** [comment]
This also shows the same behaviour when I build via "obs build" in a local chroot environment.

Also I have to revoke that this works with kiwi7. I just double checked via obs + "osc build", it also fails with kiwi7.

The only thing that is different from my perspective at the moment is, that I try to build with SLE-15 repos, instead of SLE-12 repos.

**Comment by schaefi** [comment]
yes none of osc build or build in obs can deal with lvm builds. For an unknown reason the device paths created by the lvm tools does not work inside of the chroot or worker environment from obs. I guess the kernel or the udev rules or a combination of both prevents that this works. You can try to just build with kiwi on the host instead of osc build and this under normal conditions works well as I also test this pretty often.

But be aware the above mentioned issues for lvm also applies if you build from a "normal" host. The most annoying thing here is the lvmetad which I usually replace by a /usr/bin/true when I want to use the host as build host for lvm images (yes nasty but works)

**Comment by rtamalin** [comment]
@schaefi @yeoldegrove the issue is that udev is not running in a chroot'd environment, so the devices are not automatically created for you. This causes two problems:

1. lvcreate by default tries to zero the header (4kib) of the newly created raw device, but the code that does so assumes that the device entry has automatically been created by udev, which is not the case for the chroot'd run. This can be avoided by including `-Zn` in the lvcreate options list, which disables the zeroing of the header, which should be unnecessary because the backing device is a zero filled qemu-img created file.

1. Because there is no udev running in the chrooted environment you have to explicitly run the `vgscan --mknodes` command to create the appropriate device lines under /dev so that subsequent operations can interact with the newly created device.

**Comment by rtamalin** [comment]
FYI I've published a workaround fix here: https://github.com/rtamalin/kiwi/tree/lvm_image_fixes

I'm preparing is as a pull request for fixing this issue, just need to sort out the unit testing aspects of it.

**Comment by rtamalin** [comment]
If you would prefer me to create a new issue, rather than re-opening this issue, I'll be happy to do so.

**Comment by yeoldegrove** [comment]
I would be happy about a fix in kiwi itself...
As for now I have a workaround in my local OBS to build LVM images with kiwi.

**Comment by schaefi** [comment]
Thanks for your investigations and coding effort. Yes it would be great if you can open an issue and the respective pull request with your fix. We should not forget that it should continue to work also in an env which is controlled by udev. I hope the ```mknodes``` command can be used in combination with udev generated devices.

When I did the implementation for lvm I followed the node schema

```
['/dev/', self.volume_group, '/', volume_name]
```

which is the one used by udev, but I remember LVM used the device mapper before and mknodes generated them in /dev/mapper/...

So we need to have an eye on consistency. Other than that it would be great to get it working if udev is not present.

Another lvm issue but not related to the one you have here is that the presence of the lvmetad in the system caches any volume group creation even the ones we need when we operate on loops to create the image. This results in lvm thinking the group X is already present but it was only present in a loop for a while. Switching off lvmetad force lvm to go back to internal scanning which is not cached and runs any time when needed.

There are some consistency issues between host and guest when it comes to lvm. Worst case is if the host is building the image is lvm based and you want to build an lvm image on such a host... better not do it :)

**Comment by rtamalin** [comment]
My test hosts where I'm running `osc build` locally are LVM based and work fine with the workaround.

And from what I can see the `vgscan --mknodes` is idempotent, so does nothing if the desired device entries already exist, whether as symlinks to the real device or as mknod'd devices; I can safely run it on my LVM based Leap and Ubuntu hosts without issues, and the workaround works correctly within `osc build` on both a Leap 15 and Ubuntu Xenial box.

As for the caching issue, yeah I went down that path for a while as I wasn't sure if it was contributing to the issues seen; running `pvscan --cache` or `vgscan --cache` or `lvscan --cache` will force a refresh of the respective cache entries if that is needed...

However the main issue is really that `lvcreate` has an inbuilt assumption that as soon as device mapper reports that it has successfully created the device in the kernel, then it will automatically appear on the system as a device (/dev/mapper/<vgname>-<lvname> path IIRC) and the header zeroing code assumes it can open that device to write to it, without checking that udev is actually present/active to create the device... Of course it is a very subtle/rare scenario.

I'll open a new issue and update my commit message and work on getting unit testing for this tweak working.
