### ISSUE TITLE
Profiles should be able to get grouped

### ISSUE THREAD

**Issue by agraf** [SUSE/kiwi#658]
## Problem description
When building an image description, we can potentially have multiple profiles that together make up the actual expected build target. For example, you may have profiles for "VMware", "x11_common" and "gnome". The expected build target would be "VMware-gnome" which can then combine all the targets required.

## Expected behaviour
There are multiple ideas on how to accomplish this. One idea would be to add a special "profiles group" tag in parallel to the "profiles" one that defines groups:

```
  <profilegroups>
    <profilegroup name="VMware-gnome" includes="VMware,x11_common,gnome">
  </profilegroups>
```
Another idea (probably better IMHO) would be to just allow profiles to include other profiles automatically:

```
  <profiles>
    <profile name="VMware" />
    <profile name="x11_common" />
    <profile name="gnome" />
    <profile name="VMware-gnome" includes="VMware,x11_common,gnome" />
  </profiles>
```

That's probably more consistent and easier to integrate in OBS.

@adrianschroeter @Vogtinator both can provide more ideas if needed.

## OS and Software information
+ KIWI version: 
+ Operating system: 
+ OBS version:

**Comment by Vogtinator** [comment]
It looks like your examples aren't liked by Markdown, they're not shown the web UI.

The profilegroup mechanism has too many drawbacks and shouldn't be used:

- Everything using profiles would need to be changed to also use profile groups (new parameter, `--profilegroup`)?
- Only one layer of indirection possible
- You can have profilegroups with the same name as profiles, causing conflicts
- You can't use `profiles="profile-foo,profilegroup-bar"` as a profilegroup isn't a profile

**Comment by davidcassany** [comment]
Honestly I am a bit concerned about that feature. I understand the exposed use case, but I am afraid it could cause quite complex, hard to debug and probably inconsistent description files. Keeping schema strict and clearly defined trying to prohibit any inconsistency is value we should keep.

In addition keep in mind that profiles support in OBS is currently not widely used and probably missing some logic, I don't think package resolution in OBS is already handling profiles just to mention something; and I guess several corner cases could arise.

Just quick thinking (not even sure if this can be easily implemented) but probably it could be possible and safer to make kiwi subcommand that does the job by simply outputting a plain profile-less with a single type description given one or more profiles (and an image type). This way it would be easy to script in order to create multiple config.xml files from a complex profiled description. This could be also handy for debugging.

**Comment by adrianschroeter** [comment]
On Mittwoch, 7. März 2018, 16:08:36 CET wrote David Cassany Viladomat:
> Honestly I am a bit concerned about that feature. I understand the exposed use case, but I am afraid it could cause quite complex, hard to debug and probably inconsistent description files. Keeping schema strict and clearly defined trying to prohibit any inconsistency is value we should keep.
> 
> In addition keep in mind that profiles support in OBS is currently not widely used and probably missing some logic, I don't think package resolution in OBS is already handling profiles just to mention something; and I guess several corner cases could arise.

just added that yesterday ...

I hope the support is quite complete now, also including the new architecture filtering.

> Just quick thinking (not even sure if this can be easily implemented) but probably it could be possible and safer to make kiwi subcommand that does the job by simply outputting a plain profile-less with a single type description given one or more profiles (and an image type). This way it would be easy to script in order to create multiple config.xml files from a complex profiled description. This could be also handy for debugging.

uh, that means we would need a source service again (and even kiwi version specific?) as extra layer, 
because we could not parse the kiwi file ourself again?

We just made the necessary changes to be able to life with on kiwi file providing multiple
profiles and build the defined profiles without any service again ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
KIWI can already use multiple profiles for building images (`--profile foo --profile bar`).

It just needs to be able to handle predefined combinations.

**Comment by adrianschroeter** [comment]
but this would result in two images, one built using foo and one with bar, right?

I understood  this request that one image is wanted using multiple profiles?

**Comment by Vogtinator** [comment]
> but this would result in two images, one built using foo and one with bar, right?

KIWI enables all sections in the XML file with either no `profiles` attribute or with enabled profiles in there.
You get as many images as `<type/>` elements in the description.
So if the `bar` profile only activates a `<packages/>` section, you get an image with `foo` + the packages from `bar`.

**Comment by davidcassany** [comment]
> just added that yesterday ...
I hope the support is quite complete now, also including the new architecture filtering.

Awesome, great to know.

> uh, that means we would need a source service again (and even kiwi version specific?) as extra layer, because we could not parse the kiwi file ourself again? 

Well, just wild thinking, I agree that this would not be that comfortable in OBS context. 

> KIWI can already use multiple profiles for building images (--profile foo --profile bar).

Yes you are right, I missed that this is already possible. I have just checked the code to see how they are actually merged and it looks like this is what @agraf is after. Then, given that it is already possible, I guess the whole issue is getting that possibility in an OBS context. Then @agraf suggestion:

```xml
<profile name="VMware-gnome" includes="VMware,x11_common,gnome" />
```
doesn't look bad to me, assuming this would be equivalent to a

```bash
kiwi --profile VMWare --profile x11_common --profile gnome ...
```

**Comment by Vogtinator** [comment]
> `<profile name="VMware-gnome" includes="VMware,x11_common,gnome" />`
> doesn't look bad to me, assuming this would be equivalent to a
> `kiwi --profile VMWare --profile x11_common --profile gnome ...`

Close: `kiwi --profile VMware-gnome --profile VMWare --profile x11_common --profile gnome ...`
as it should still be possible to have `<packages profiles="VMware-gnome"/>`, for instance.

It would in theory be possible to implement this in OBS only, but adding support in KIWI is IMO cleaner, more extensible and also means that the images can be built from outside OBS easily.

**Comment by davidcassany** [comment]
> You get as many images as <type/> elements in the description.

When multiple types are present and type is not defined, the one with `primary` attribute is used. If none has the `primary` attribute then first match is used. So you get a single image.

**Comment by davidcassany** [comment]
> Close: kiwi --profile VMware-gnome --profile VMWare --profile x11_common --profile gnome ...
as it should still be possible to have <packages profiles="VMware-gnome"/>, for instance.

Good point, you are right.

**Comment by Vogtinator** [comment]
> When multiple types are present and type is not defined, the one with primary attribute is used. If none has the primary attribute then first match is used. So you get a single image.

Ok, then what I saw was a bug, for some reason it built a mix of both `<types/>`.

**Comment by davidcassany** [comment]
> Ok, then what I saw was a bug, for some reason it built a mix of both <type/>s.

:disappointed: I'll make some real trials and see, hopefully nothing bad.

**Comment by adrianschroeter** [comment]
so, calling kiwi with multiple --profile options is what we want? 

I could extend the obs-profile hint, which we parse from kiwi files to support things like this:

 `<!-- OBS-Profiles: KDE_VMWARE(VMware,KDE) RaspPi(RaspberryPi,JeOS,TouchPad) -->`

which would basically do the same ... not sure what is nicer .....

**Comment by Vogtinator** [comment]
Which means you would then need to define those profiles twice, once in the comment for OBS and once in the description for kiwi.

Also, how would that work together with multibuild?
Currently it says:

`<!-- OBS-Profiles: @BUILD_FLAVOR@ -->`

Which AFAICT means: Use `@BUILD_FLAVOR@` as the profile.

Additionally, it's not easy to tell what happens with `RaspPi` in your example, knowing that `RaspberryPi` has `arch=aarch64`:
- Don't build `RaspPi` for x86_64 because a referenced profile doesn't get enabled
- Build `RaspPi` for x86_64 but exclude `RaspberryPi`?

IMO this makes it only more complicated, so it should be implemented in kiwi as profile extension.

**Comment by adrianschroeter** [comment]
we can make it work, but I agree it would be nice if kiwi would support it directly. Also because you could get same builds using plain kiwi.

**Comment by schaefi** [comment]
From a definition point of view what is requested here are profile groups with a name which I would declare as follows:

```xml
<profiles>
    <profile name="a"/>
    <profile name="b"/>
    <profile name="c"/>
    <profile name="z"/>
    <group name="gnome">
        <include profile="a"/>
        <include profile="z"/>
    </group>
</profiles>
```

The current way to select a profile with --profile a --profile z is of course still valid but you could also select by group name or combination and I suggest to have an extra option for it, e.g --profile-group gnome

* This could be added relatively easy to the schema
* Validation if group included profile is defined could be done on the parser level

Thoughts ?

**Comment by Vogtinator** [comment]
Those two advantages are also valid for the uniform "profiles can include other profiles" approach, aren't they?

It would be useful to have groups which in turn include other groups.

**Comment by adrianschroeter** [comment]
@Vogtinator yes, but it increases also the complexity a bit when coding support, because groups allow just 1 level deep inclusion ...

on the other hand, handling with groups beside profiles is doing as well. means we would need also an OBS-Group hint for OBS to support kiwi groups.

however, I am fine with both ways, the way @Vogtinator proposed would be way more powerful, but we would need to handle recursive inclusion and we would need also a cycle detection (in kiwi and OBS).

**Comment by schaefi** [comment]
I don't really like the "profiles can include other profiles" approach because it's hard to read and even in this discussion the result list of profiles was not obvious or let's say easy to overlook. recursion and cycle detection sucks, sorry :)

I rather go with a bit more redundancy than with profile cascades and deep recursion

**Comment by adrianschroeter** [comment]
k, @schaefi, could you make it in a way that it does not matter if the name in a profile or a group then?

means that kiwi --profile XXX would match group or profile, so we don't need new interfaces?

Means of course you can not have a group with the same name as a profile ...

**Comment by Vogtinator** [comment]
> however, I am fine with both ways, the way @Vogtinator proposed would be way more powerful, but we would need to handle recursive inclusion and we would need also a cycle detection (in kiwi and OBS).

> I don't really like the "profiles can include other profiles" approach because it's hard to read and even in this discussion the result list of profiles was not obvious or let's say easy to overlook. recursion and cycle detection sucks, sorry :)

It's trivial as it's unconditional: Just check whether the profile you're adding was already added.

**Comment by schaefi** [comment]
> It's trivial as it's unconditional: Just check whether the profile you're adding was already added

It's immaterial if it's trivial, it's imho not needed and I don't see a reason for nested profiles. To be honest I don't want people to even think about the possibility. When you design an image description you do it in the most simple way, you use the smallest possible package list, you try to use less to no profiles to keep the number of indirection small, you try to handle one target and you want to do this explicit without having the need to recursively go back in a nested profile structure to see a list of names which should just be presented to you by one short look. An image description is just reading no thinking and no unneeded complexity please. Reading the same thing twice does not hurt

> k, @schaefi, could you make it in a way that it does not matter if the name in a profile or a group then? means that kiwi --profile XXX would match group or profile, so we don't need new interfaces? Means of course you can not have a group with the same name as a profile ...

Well you are suggesting that because it makes the use of the feature on the obs side easier. From an implementation point of view it feels odd that a group name is the same than a profile name. Don't get me wrong but magic assumptions behind the scene is one of the reasons why the perl version of kiwi turned into bad shape. Maybe you can imagine that we (and @davidcassany  please object when I'm wrong) are not motivated to drive the implementation with changing the meaning of the --profile option

Thanks

**Comment by Vogtinator** [comment]
> It's immaterial if it's trivial, it's imho not needed and I don't see a reason for nested profiles

I do.

```
<profile name="Minimal-X-RPi" includes="RaspberryPi,Minimal-X"/>
<profile name="RaspberryPi" arch="aarch64"/>
<profile name="Minimal-X" includes="JeOS"/>
<profile name="JeOS" />
```

IMO treating groups as profiles is much easier, even in the implementation.

**Comment by schaefi** [comment]
We are not talking about the implementation, this part is easy no matter what decision we make.

We will not change the meaning of profile as it is public today. A profile group is not a profile, it's a list of profiles and I don't want to mix profile definitions with group definitions.

I thought the intention here was to add a group name layer for profiles. The above example is no group at all it's a chain of profiles depending on which starting profile is selected. The result chain has no name and is not explicitly defined. Thinking that this list would grow with references to references of other profiles it will just become confusing

**Comment by Vogtinator** [comment]
> I thought the intention here was to add a group name layer for profiles. The above example is no group at all it's a chain of profiles depending on which starting profile is selected.

Both would work, but the chain is more flexible and would result in easier to maintain profiles.
So if you split a profile in two for some reason, you only need to add it once instead of in every referenced profile.

All of this is just "syntactic sugar" on top of `<package profiles="foo,bar"/>` anyway, with the benefit of a simple interface to OBS and users.

> The result chain has no name and is not explicitly defined.

It has the same name as the profiles mentioned on the cmdline.
Currently you don't have a name for the "result chain" for `--profile foo --profile bar` either.

> Thinking that this list would grow with references to references of other profiles it will just become confusing

Why? It's still only single list of profiles.

**Comment by schaefi** [comment]
> Currently you don't have a name for the "result chain" for --profile foo --profile bar either.

correct and that's what I thought are you aiming for. You define profile groups in the image and instead of a collection of "--profile x11 --profile xdrivers ..." in the kiwi call you specify the group name --profile-group gnome and be done

I'm ok adding this additional group information but I don't want to allow a profile dependency chain and along with it changing the behavior of what --profile means today. I still think the include way you suggested is hard to read, the result chain needs to be interpreted by the reader, it's not obvious especially if there are many profile elements. The argument that a change of a profile affects group definitions is also valid for include statements.

Last but not least, if it's not the grouping information which counts but more the profile dependencies I question if this is something an image description has to define ? I mean the collection of profiles to allow customizing the image is clearly something you need in the image description. The combination of profiles to fit the user needs depends on what the user wants to build and is a caller responsibility which is supported by kiwi --profile a --profile b --profile c .... So obs as the caller knows what profiles it needs and imho calls it that way already. why do we need the dependency information in the image description ?

**Comment by Vogtinator** [comment]
> So obs as the caller knows what profiles it needs and imho calls it that way already. why do we need the dependency information in the image description ?

Because OBS doesn't have it in any other format.
It should also be possible to build the image easily without obs.

**Comment by schaefi** [comment]
> It should also be possible to build the image easily without obs.

That part would be covered by an additional group definition. Correct me if I'm wrong but profiles are currently specified in the project config and the build script takes it from there and creates a bunch of --profile arguments from it, is that correct ?

If so where does the requirement to create a dependency chain where one profile includes another
one come from and why is this now important ? 

> Because OBS doesn't have it in any other format.

This I don't understand

**Comment by Vogtinator** [comment]
> That part would be covered by an additional group definition. Correct me if I'm wrong but profiles are currently specified in the project config and the build script takes it from there and creates a bunch of --profile arguments from it, is that correct ?

Not anymore, this got changed last week (not documented...):
OBS parses the .kiwi file and if told, builds each profile separately using `_multibuild`.
It can also only pass a single `--profile` argument.

> If so where does the requirement to create a dependency chain where one profile includes another
one come from and why is this now important ?

We want to consolidate several images into a single .kiwi file for easier maintenance.

> > Because OBS doesn't have it in any other format.
>
> This I don't understand

OBS only has the .kiwi file for information about the profiles - there's nothing else it can derive more information about dependencies from. Putting it in the prjconf would break other images in the same project.

**Comment by schaefi** [comment]
ok now I understand the reason behind this. So this is not really about adding a group layer, you need profile dependencies and obs will read that information from the description directly. In this case I suggest a slightly more markup like style:

```xml
<profile name="VMware-gnome">
    <requires profile="VMware,x11_common"/>
    <requires profile="gnome"/>
</profile>
```

The requires element is optional and --profile VMware-gnome will pull in the required profiles.
It's still a behavior change of the current profile handling but given to the information you provided there seems to be no other way

**Comment by davidcassany** [comment]
> That part would be covered by an additional group definition. Correct me if I'm wrong but profiles are currently specified in the project config and the build script takes it from there and creates a bunch of --profile arguments from it, is that correct ?

If it has not changed recently this not the OBS behavior, if multiple profiles are provided via prjconf (I am not aware of any other way to target profiles in OBS, i.e. `BuildFlags: kiwiprofile:vmware,kvm`), it just results in multiple builds, each one with a single `--profile` flag. Thus the result is one image per profiles included in the conf.

**Comment by Vogtinator** [comment]
> It's still a behavior change of the current profile handling but given to the information you provided there seems to be no other way

I'm not sure how this is a behaviour change: Existing kiwi profiles and parameters will just work the exact same way as they don't have any dependencies.

> If it has not changed recently this not the OBS behavior, if multiple profiles are provided via prjconf (I am not aware of any other way to target profiles in OBS, i.e. BuildFlags: kiwiprofile:vmware,kvm), it just results in multiple builds, each one with a single --profile flag. Thus the result is one image per profiles included in the conf.

Exactly that changed now, you can combine it with _multibuild.

**Comment by schaefi** [comment]
> I'm not sure how this is a behaviour change:

Using --profile might pull in other profiles, that's a change in behavior and needs to be documented. You are right without a change to existing descriptions the same kiwi call will produce the same result.
Anything else we also would not accept :)

**Comment by davidcassany** [comment]
>ok now I understand the reason behind this. So this is not really about adding a group layer, you need profile dependencies and obs will read that information from the description directly. In this case I suggest a slightly more markup like style:

>```xml
><profile name="VMware-gnome">
>    <requires profile="VMware,x11_common"/>
>    <requires profile="gnome"/>
></profile>```

Ok, in that case, I would assume the `VMWare-gnome` profile it can also be used as a `profile="VMware-gnome"` in other tags.

**Comment by schaefi** [comment]
Well yes including all the nasty things like dep loops and such but it's not hard to break the loop if present

**Comment by davidcassany** [comment]
Allright, I'll start with it then

**Comment by schaefi** [comment]
Ok great, thanks

**Comment by davidcassany** [comment]
@agraf With the following release it will be possible to group profiles with the following syntax:

```xml
<profiles>
    <profiles name="profile1"/>
    <profiles name="profile2"/>
    <profile name="groupped">
        <requires profile="profile1"/>
        <requires profile="profile2"/>
    </profile>
</profiles>
```

**Comment by agraf** [comment]
Perfect. Please make sure that one lands in SLE15 :)
