### ISSUE TITLE
invalid shebang for `kiwi/xml_parse.py` (also, says py2 compatible when isn't!)

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#666]
## Problem description

In [the package review for kiwi for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1483339), the following issue came up from @decathorpe:

>The file "kiwi/xml_parse.py" has "#!/usr/bin/env python" shebang, which is wrong and must be replaced by "#!/usr/bin/python3" (sic!) and the file marked as executable, or the shebang should be removed entirely (for both the python2 and python3 version). That file isn't even compatible with python2, so ... I guess that should be fixed upstream.

## OS and Software information
+ KIWI version: 9.13.7
+ Operating system: Fedora 27

**Comment by davidcassany** [comment]
About the shebang presence I am wondering why is it offensive, IMHO it doesn't hurt and I'd prefer to leave auto-generated code untouched. GenerateDS creates a code that can be run and tested as a script and even we do not need that feature I don't really see why we should change that. If the auto-generated code includes

```python
if __name__ == '__main__':                                                      
    main()
```
I think is correct to have a shebang.

In the worst case we could always remove the first line of that file in the Makefile, but it looks like an ugly hack to me.

Anyway, @Conan-Kudo thanks much for reporting us back this feedback here and your efforts to get kiwi into Fedora.

**Comment by decathorpe** [comment]
The file having a shebang isn't the issue per se. However, having a shebang implies that the file can be executed as a script - which it can't, because it doesn't even have the executable bit set. rpmlint complains about this discrepancy.

Either way, this shebang has to be patched (and the file set as executable) - or removed - for fedora to comply with the Packaging Guidelines for python, which ban the use of `#!/usr/bin/env python` and unversioned `#!/usr/bin/python`. To quote the guidelines [0]:

> (...) `/usr/bin/python` (as well as `/usr/bin/env python` and similar) MUST NOT be used in shebang lines (...)

I don't care whether the fix occurs upstream or in a downstream patch.

Side note: I might be wrong about the python2 incompatibility.

[0]: http://fedoraproject.org/wiki/Packaging:Python#Multiple_Python_Runtimes

**Comment by davidcassany** [comment]
@decathorpe, thanks much for your feedback. I'll think about it there must be a solution.

**Comment by Vogtinator** [comment]
Note that we have the same policy in openSUSE - so this apparently got ignored during the submission process.

It still shows:

```
python2-kiwi.x86_64: W: non-executable-script /usr/lib/python2.7/site-packages/kiwi/config/functions.sh 644 /bin/bash
python3-kiwi.x86_64: W: non-executable-script /usr/lib/python3.6/site-packages/kiwi/config/functions.sh 644 /bin/bash
```

**Comment by davidcassany** [comment]
> It still shows:

```
python2-kiwi.x86_64: W: non-executable-script /usr/lib/python2.7/site-packages/kiwi/config/functions.sh 644 /bin/bash
python3-kiwi.x86_64: W: non-executable-script /usr/lib/python3.6/site-packages/kiwi/config/fun
```

Yes in fact this has been solved in #670 for the functions script and for the dracut modules scripts. In this concrete case we have a rpmlint filter to ignore the complaints for `kiwi/xml_parse.py` as this is auto-generated code. See that we have a `package/python-kiwi-rpmlintrc` that includes:

```bash
# don't blame on auto generated code
addFilter("non-executable-script .*/xml_parse.py.*")
```
@decathorpe, @Conan-Kudo I am wondering if this was used in the Fedora build and if this would be an acceptable solution. The other offending shebangs have been already rearranged, this one I'd like to leave it as is, since it is an auto-generated code. Would it be possible to make use of such rpmlint filter?

**Comment by Conan-Kudo** [comment]
I just strip it in the spec: https://src.fedoraproject.org/rpms/kiwi/blob/master/f/kiwi.spec#_233-234

**Comment by schaefi** [comment]
I would be ok with a change in our spec file which does the same

**Comment by schaefi** [comment]
@davidcassany hope you don't mind I set you as assignee here, since you already fixed the other shebang issues. If not ok, just delete the assignment and put me in :)

**Comment by davidcassany** [comment]
@schaefi, sure no problem :) that's fine.
