### ISSUE TITLE
dracut module shell script files for kiwi-lib have shebangs when they shouldn't

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#668]
## Problem description
In [the package review for kiwi for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1483339), the following issue came up from @decathorpe:

> 8) dracut modules (in "/usr/lib/drac7t/modules.d/99kiwi-lib/*" have bash shebangs, but aren't marked as executable. Is that correct?

These files are purely functions and should not have shebangs, since there's nothing useful to execute.

## OS and Software information
+ KIWI version: 9.13.7
+ Operating system: Fedora 27

**Comment by davidcassany** [comment]
I don't have arguments to keep shebangs here, but I'd prefer to leave it as is if possible.

I like them there because it clearly advises it uses bash syntax to any potential contributor and also because it works well with [shellcheck](https://www.shellcheck.net/), otherwise we need to specify on shellcheck parameters which shell to validate (which somehow enforces my argument of having it explicit within the file).
