### ISSUE TITLE
Removing dracut-kiwi-live fails on dependency %preun

### ISSUE THREAD

**Issue by mkrawiec** [SUSE/kiwi#695]
## Problem description
Since 22.03.2018 dracut-kiwi-live requires `xorriso`. On openSUSE `xorriso` has custom `%preun` hook that expects info files present in `/usr/share/info`, but kiwi strips this directory to save space. Upon removing the package, this causes the hook to fail and the whole zypper command fails as well. So after the appliance is created, dracut-kiwi-live cannot be removed with clearing it's dependencies.

    Error: Subprocess failed. Error: RPM failed: install-info: No such file or directory for /usr/share/info/xorrecord.info.gz
    error: %preun(xorriso-1.4.6-lp150.1.4.x86_64) scriptlet failed, exit status 1
    error: xorriso-1.4.6-lp150.1.4.x86_64: erase failed

## Expected behaviour
`dracut-kiwi-live` and `xorriso` should be possible to uninstall after appliance is created.

## Steps to reproduce the behaviour
    zypper in dracut-kiwi-live
    rm /usr/share/info/xorrecord.info.gz 
    zypper rm dracut-kiwi-live xorriso

## OS and Software information
+ KIWI version: 9.14.0
+ Operating system: openSUSE Leap 15
+ OBS version: N/A

**Comment by davidcassany** [comment]
@mkrawiec I believe this might more a xorriso package issue rather than a KIWI issue, in fact I doubt we can do much about it. It is not that KIWI strips `/usr/share/info/*` files, it is zypper (and the underlying rpm binary) that does not install them when the `excludedocs` flag is activated. Thus if you include `<rpm-excludedocs>false</rpm-excludedocs>` in your preferences this issue should not appear anymore.

IMHO this is a xorriso package issue. Looks like xorriso does not have a %preun scriplet compatible with the excludedocs RPM flag.

**Comment by mkrawiec** [comment]
@davidcassany Thank you for the update. I reported the issue on opensuse bugzilla: https://bugzilla.opensuse.org/show_bug.cgi?id=1089175
