### ISSUE TITLE
Container Image Build - Support for Multiple Tags

### ISSUE THREAD

**Issue by sysrich** [SUSE/kiwi#713]
## Problem description

Kiwi doesn't support having multiple tags for a container image build

## Expected behaviour

It should be possible to build container images with multiple tags

**Comment by davidcassany** [comment]
@sysrich this is not a problem if the underlying tools can handle that. @cyphar, @vrothberg do you have any hint about how to do that with `skopeo` and `umoci`.

**Comment by cyphar** [comment]
`umoci` supports multiple tags in a single image for OCI images. However, `skopeo` doesn't allow you modify a `docker-archive` image in-place (modifying `tar` archives in-place is very close to an unsolvable problem). A `docker-archive` image can hold more than one tag, but there's no UX at the moment to allow you to do that (and I have a bad feeling that the internal reworks necessary in `skopeo` to make that work will be quite large). In theory if we weren't shipping Docker images this wouldn't be as much of an issue.

Another possible solution would be to add `docker-dir` as a format, which we could then `tar` ourselves. But this would also require a lot of work (the reason why `docker-archive` was easier to implement is because it just required refactoring `docker-daemon` -- `docker-dir` would be far more complicated).

**Comment by vrothberg** [comment]
Couldn't we add an option to `skopeo-copy` (and backport the patch if required) to provide additional tags? It seems that the reference handling of skopeo is based on the tags, so an adding an option looks like a promising solution to me.

**Comment by davidcassany** [comment]
@vrothberg, if skopeo can be extended for that then from KIWI side it should not be a big deal in terms of implementation. We should just make sure it is a maintainable solution for skopeo, which in IMHO means that is adopted by the upstream project, but anyway, I am not the expert about skopeo :P

**Comment by schaefi** [comment]
yes if skopeo-copy can do it that would be a clean way for kiwi to provide the implementation. As multiple tags needs to be specified in the image description this would also imply that a build will fail if skopeo-copy does not provide the needed functionality. I would appreciate an easy way to identify the capability before the build starts.

**Comment by cyphar** [comment]
@davidcassany My comment was referring to that feature being added to `skopeo`. I wouldn't suggest adding these sorts of hacks to `kiwi. :wink:

@vrothberg I mentioned that in my comment:

> A `docker-archive` image can hold more than one tag, but there's no UX at the moment to allow you to do that (and I have a bad feeling that the internal reworks necessary in `skopeo` to make that work will be quite large).

To expand on what I said, (as far as I can tell) it would require changing the `containers/image` `ImageDestination` (and possibly `ImageSource`) APIs to support multiple references (in a way that would allow `skopeo copy` to be significantly modified to handle copying of multiple references in one go). This would probably require modifying each image transport as well as the `containers/storage` pseudo-transports (and the `cri-o` users depending on wherther we add something to the API or change an exising one). In my view this is probably not the best way of doing it.

i think that something like `docker-dir` would be *less* complicated to implement (and because it's not a linear archive the modification problem basically goes away for the most part -- though the code for pruning un-used layers would need to be added). Then `kiwi` could just `tar` up the resultant artefact just like we do for `oci` images.

**Comment by vrothberg** [comment]
@cyphar Thanks, for the nice explanation.

I just had a close look at `containers/image`'s copy/transport code and my conclusion aligns with yours: _getting this upstream may not be the best way as effectively the entire library is built around the notion of having a single reference._ However, I think it's possible to avoid changing any signature as additional tags could be specified in the `Options` type. In case of a docker-archive, it seems pretty straight-forward to add multi-tag support, but having a generic approach for all transports could be hairy.

**Comment by Vogtinator** [comment]
I don't know much (anything, really) about skopeo interrnals, so I might be wrong entirely.
The way I implemented multiple tags easily in the openSUSE docker registry push bot was by essentially pushing the same image twice, with a different reference. It noticed that except for the tag everything was already present, so only a single `PUT` had to be made. I assume something like that would work for skopeo as well, essentially calling `skopeo copy` twice for the same image.
The second call would then notice the image contents already exists and only add the new reference.

**Comment by vrothberg** [comment]
@Vogtinator That works for registries but in case of a docker-archive, multiple copy operations would create multiple tar archives but we need only one. In our specific case, the `manifest.json` in the generated archive must contain the specified tags in the `RepoTags` field.

**Comment by vrothberg** [comment]
The support for containers/image has been merged. Here's the PR for skopeo: https://github.com/projectatomic/skopeo/pull/501

**Comment by davidcassany** [comment]
Great! So having the containers/image#447 merged upstream makes us confident enough to start working on the KIWI side. I'll try to use the updated skopeo and check it works fine for us and that it is easy to check and verify multitag support.

Thanks @vrothberg

**Comment by davidcassany** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for multitags in Kubic images](https://trello.com/c/U7hljc8y/856-add-support-for-multitags-in-kubic-images)

**Comment by davidcassany** [comment]
I have been thinking that probably a good way to provide multiple tags in KIWI schema could be by adding a new attribute for `<containerconfig>` in schema. Something like:

```xml
<type image='docker'>
  <containerconfig name="kubic/mariadb" tag="current" additional_tags="10.2.3,someothertag"/>
</type>
```
I prefer that than having to parse multiple tags in `tag` (also having to rename it to `tags`) attribute as comma separated values. This would be a quite intrusive change on how `containerconfig` works up to now.

Another option to consider could be using new child `containerconfig` entities:

```xml
<type image='docker'>
  <containerconfig name="kubic/mariadb" tag="current">
    <additional_tags>
      <tag name="10.2.3"/>
      <tag name="someothertag"/>
    </additional_tags>
  </containerconfig>
</type>
```
But I find it very verbose.

@sysrich, @schaefi, any thoughts?

**Comment by davidcassany** [comment]
@vrothberg I have some doubts about the implication of these multi-tag feature for skopeo.

Is there going to be any difference between the inherited tag from the OCI image in comparison to the ones added by the `--additional-tag` flags?

Given a config like:

```xml
<containerconfig name="container_name" tag="container_tag" additional_tags="extra_tag"/>
```

Kiwi would end up calling something like:

```bash
skopeo copy oci:umoci_layout:container_tag docker-archive:image_tarfile:container_name:container_tag --additional-tag extra_tag
```

There would be any difference if

```bash
skopeo copy oci:umoci_layout:extra_tag docker-archive:image_tarfile:container_name:extra_tag --additional-tag container_tag
```

is called instead? (assuming the OCI image is already tagged with all them)

**Comment by vrothberg** [comment]
@davidcassany Do you mean if there's a semantical difference between the tag in the source reference (e.g., `docker-archive:foo.tar:foo:latest`) and the additional tags? To the best of my knowledge, there shouldn't be a difference as all of them will end up in the `RepoTags` field in the `manifest.json` file of the generated docker archive.  If we do a `docker-load`, the underlying image(s) will be tagged with all tags in the `RepoTags` field.

**Comment by vrothberg** [comment]
For skopeo, the tags in the source reference (e..g, the OCI image) are more or less irrelevant for the destination image. Before the new additional-tag-PR, only the tag in the destination reference was used (regardless of the source tags).
