### ISSUE TITLE
Please support a <license> field in kiwi build description

### ISSUE THREAD

**Issue by adrianschroeter** [SUSE/kiwi#728]
## Problem description

Legal review of build descriptions requires a defined license.

## Expected behaviour

We would like to have a license field as part of build descriptions which can be used with SPDX defined licenses:  https://spdx.org/licenses/

**Comment by davidcassany** [comment]
@adrianschroeter, at glance, I think I misunderstood the request. You are asking to be able to include some kind of license field in `config.xml` description file, right? If so, what shall we do with it? Where should we copy or include the License inside the image?

Initially I thought you were asking to fix the KIWI license to match one of the SPDX list (which I guess is something that should be fixed in KIWI spec, together with the usage of `%license` marco)

**Comment by adrianschroeter** [comment]
To be clear, this tag will state only the license of the build scripts - not the license of the contents, right? If so, the tag should be properly named. Simply calling it "license" will just cause confusion.
________________________________________

**Comment by Conan-Kudo** [comment]
I would probably suggest it shouldn't mandate SPDX form license identifiers. Between [Fedora license tags](https://fedoraproject.org/wiki/Licensing:Main#Software_License_List) (used by nearly all RPM-based distros except openSUSE) and custom things for proprietary licenses both being in common use, it'd be very inflexible for regular use.

**Comment by davidcassany** [comment]
@Conan-Kudo, fair enough it makes sense to not limit the license to SPDX identifiers, I don't see any reason to limit propietary licenses or any other custom license.

>  Thus I would say the following should work for you:

> ```xml
> <description type="system">
>         ...
>         <license>some-license-name</license>
> </description>

@adrianschroeter, could you confirm that the above would solve your issue?

**Comment by adrianschroeter** [comment]
I think that is what was requested. You might want to ask Ciaran maybe directly.
