### ISSUE TITLE
KiwiCompressionFormatUnknown: could not detect compression format for /containers/SUSE:Templates:Images:SLE-12-SP3:Base/images/container:SLE-12-SP3-Container-Base.tar

### ISSUE THREAD

**Issue by toabctl** [SUSE/kiwi#730]
## Problem description
OBS has now container templates (see SUSE:Templates:Images:SLE-12-SP3/SLE-12-Container-kiwi ) and one template is based on kiwi. Since yesterday, the kiwi container no longer builds:
```
[   94s] [ ERROR   ]: 16:34:37 | KiwiCompressionFormatUnknown: could not detect compression format for /containers/SUSE:Templates:Images:SLE-12-SP3:Base/images/container:SLE-12-SP3-Container-Base.tar
```

## Expected behaviour
Given that the default templates are linked on the front page, I would expect that theses templates always build without problems. So please test against theses templates before releasing a new kiwi version. My experience with kiwi/OBS so far is not very good. I look every ~2 month at building containers with kiwi and OBS and there is always some sort of problem (that get's fixed quickly, thanks for that! but it is annoying..)

**Comment by davidcassany** [comment]
Gonna have a look at it. I believe what happens is that KIWI expects only *.tar.xz compressed images. If so I agree that it should be capable to use also plain tarballs without compression, since this is the result of `docker save -o myimage.tar` and also because of #725 . Kiwi should be capable to use straight forward images coming from a docker daemon, this would be a nice enhancement.

Anyway, in this case, I think the root cause is that the base image being used in that derived image changed format, at least from `*.tar.xz` to `*.tar`. So, something changed in former base image which is build using a Docker file if I am not mistaken (see SUSE:Templates:Images:SLE-12-SP3/SLE-12-Container). The failure is not caused by a KIWI update.

@schaefi, are you working to support non compressed base images in the scope of #725. If no we can easily handle that in a separate PR. We should not have any overlay I think, the code of root_import is independent of the container creation.

**Comment by schaefi** [comment]
@davidcassany yes I'm working on that part

and yes this problem is caused by a change of the base image builds and not by kiwi

**Comment by schaefi** [comment]
> I look every ~2 month at building containers with kiwi and OBS and there is always some sort of problem...

hope you also head out to the other people involved here. kiwi is always in the poor position to be the collector for problems not always caused by us. Receiving all the complaints is also annoying... nevertheless we continue make our part as stable as possible, but if people continue cutting the branch we are sitting on it will stay annoying. sorry

**Comment by davidcassany** [comment]
> yes I'm working on that part

OK, then this issue will be solved together with #725

**Comment by schaefi** [comment]
yes

**Comment by toabctl** [comment]
> hope you also head out to the other people involved here. 

yes
> kiwi is always in the poor position to be the collector for problems not always caused by us.

I know

> Receiving all the complaints is also annoying...

yeah. Sorry for complaining. And given that I retry from time to time means that I still like kiwi! :-)

> nevertheless we continue make our part as stable as possible, but if people continue cutting the branch we are sitting on it will stay annoying. sorry

sure. But would it be possible to test against theses templates so failures like this get detected directly (at least with the next PR if something in OBS breaks kiwi).

**Comment by toabctl** [comment]
btw. thanks for fixing it!
