### ISSUE TITLE
Persistent hybrid ISO broken with firmware="bios" and virtio cdrom storage

### ISSUE THREAD

**Issue by lachs0r** [SUSE/kiwi#74]
(Sorry, accidentally opened this issue on the openSUSE/kiwi tracker at first. Maybe that one should be disabled?)

When trying to boot a hybrid ISO with persistent storage that was created with firmware="bios" in qemu with the read-only ISO in a virtio drive, LinuxRC tries to partition the disk with fdisk (which does nothing) and consequently waits for the non-existent persistent partition to appear.

In the firmware="bios" case, the devices /dev/vda and /dev/vda2 exist and LinuxRC tries to create the persistent partition as /dev/vda1. This fails because the device is read-only.

Possible workaround: Check /sys/class/block/$(basename $device)/ro for whether the device is actually writable, and disable persistence if it is not.

**Comment by lachs0r** [comment]
And now I’ve noticed that this is a completely different project from what I’m running. Sorry about the noise! :(

**Comment by lachs0r** [comment]
And now I’ve confirmed that it’s still an issue.

**Comment by schaefi** [comment]
Could you send the /var/log/boot.kiwi file after boot, it helps me to find out why you see the waiting for the device to appear

actually in the code there is the setup of a $partitionerWriteStatus variable. I use the partitioner to check if it was possible to create the write space or not. A negative exit code causes the deactivation of the write persistency and also prevents the waiting for the device to appear

checking sys/class capabilities is something I had before but it has turned out there are more possible error conditions for the creation of the write partition which can all be found when actually trying to create the partition

Something went wrong in your case, I guess parted came back with exit code 0 even on error
Just guessing, thus the log would be helpful

Thanks

**Comment by lachs0r** [comment]
Doesn’t it use fdisk in interactive mode in the BIOS case? It didn’t *print* any errors there at least. Anyway, I’ll check the boot log later today.

FWIW, making it disable persistency in this case worked with old kiwi, but with kiwi-ng it fails to mount the RW partition, so I guess further debugging will be necessary. Didn’t check the log yet, but what was immediately apparent was that the partition order is wrong (it uses the first partition instead of the second for the system, so there’s no Windows compatibility and linuxrc still seems to assume that there is no first partition). Fixing that (by calling isohybrid with the correct arguments) still didn’t make it boot however.

**Comment by schaefi** [comment]
I started to test this for the following two types

* EFI capable hybrid iso
* bios (no efi) capable hybrid ISO

I would expect the first to use parted to create the write partition (fdisk doesn't have GPT support)
I would expect the second to use fdisk

Starting with the first

**Comment by schaefi** [comment]
Result for first test with kiwi version 8.15.3

descriptions taken from here: https://github.com/SUSE/kiwi-descriptions


```
sudo kiwi-ng --color --type iso system build --description ~ms/Project/kiwi-descriptions/suse/x86_64/suse-leap-42.1-JeOS/ --target-dir /tmp/mytest
```

```
qemu-img create mydisk 10g
dd if=LimeJeOS-Leap-42.1.x86_64-1.42.1.iso of=mydisk conv=notrunc

qemu-kvm mydisk

==> kiwi_hybridpersistent=true at the boot prompt (did not had added it to the XML)
```

The system boots up and setup /dev/sda3 as the write partition

```
mount | grep sda
/dev/sda2 on /livecd type iso9660 (ro,relatime)
/dev/sda3 on /read-write type ext4 (rw,nodiratime,relatime,stripe=128)

mount | grep overlay
overlay on / type overlay (rw,relatime,lowerdir=/read-only,upperdir=/read-write/rw,workdir=/read-write/work)
```

This is the expected behaviour for EFI hybrid iso's. The write partition is not at first because not configured as fat and EFI requires first partition to be fat. the partition numbering must be in line with the geometry when using parted, thus at the moment the third partition is used and numbered appropriately. See support for exfat if you are interested in more options on this topic: https://github.com/openSUSE/kiwi/commits/ffdcded470f9c3cd87b6fc820baf1f92aaead154

**Comment by schaefi** [comment]
next testing the bios case

**Comment by lachs0r** [comment]
Remember to use VirtIO disks, e.g. `-drive file=image.iso,if=virtio,media=cdrom`.

**Comment by schaefi** [comment]
ok

**Comment by schaefi** [comment]
ah now I see your point. The iso virtio emulation is causing this. ok I'll debug this
