### ISSUE TITLE
Add a loopback.cfg to Live ISOs

### ISSUE THREAD

**Issue by probonopd** [SUSE/kiwi#752]
## Problem description

I would like to see a `loopback.cfg` file on each ISO produced by kiwi-ng. A `loopback.cfg` is basically just a `grub.cfg` that's designed to be used to boot a live distribution from an iso file on a filesystem rather than an actual physical CD.

This is a standard that has been adopted by several distributions by now, most notably the Ubuntu familiy of distributions.

## Expected behaviour

From https://www.supergrubdisk.org/wiki/Loopback.cfg:

>  What problem is it trying to solve?
>
> First some background:
> 
> Most GNU/Linux distributions' LiveCDs support being booted with the iso file on a hard drive, without needing to actually burn the image to a CD. This works not by "chainloading" the iso (which is impossible) but by extracting the kernel from the iso, either before hand or at boot time with grub2's "loopback" command. The kernel is then passed a parameter that tells it that it needs to look for its root not in /dev/cdrom, but by loop mounting an iso file. This parameter also tells the kernel (more precisely the initrd scripts) what path the iso can be found at.
> 
> The problem is that to actually boot such a distribution you need to know the path to the kernel / initrd within the iso, the particular kernel parameter that distribution uses to specify the path to the iso, and any other kernel parameters relevant to the distribution. Even knowing that, when you boot the iso you don't get the menu and options you'd get when booting the CDROM. With a loopback.cfg you get the full menu of options at boot and don't have to worry about differences between different distributions. 

This would make the life much easier for tools like [SystemImageKit](https://github.com/probonopd/SystemImageKit) that boot Live ISOs from disk.

![](https://user-images.githubusercontent.com/2480569/40770499-5a187484-64aa-11e8-88a6-76f903c8cd29.png)

cc @Vogtinator

**Comment by davidcassany** [comment]
Just in case you missed, booting the ISO file from grub2 is actually possible with current ISOs, see #585 and [deploy iso image as file docs](http://suse.github.io/kiwi/building/working_with_images/iso_to_usb_stick_file_based_deployment.html).

Reading the [link](https://www.supergrubdisk.org/wiki/Loopback.cfg) you passed I have some doubts about what we gain including the loopback.cfg. As far as I can see we only gain the option of using the isodetect.lua in order to get autogenerated menu entries with host grub2. Is that right?

**Comment by probonopd** [comment]
Yes, it is already possible to loop-mount but having a `loopback.cfg` would make it easier for third-party tools to put together the needed grub entries. There are more [such](https://www.pendrivelinux.com/) third-party tools than I can count.

**Comment by davidcassany** [comment]
@probonopd I have been having a look at it and I did not manage to get it working with the `autoiso.cfg` script provided by grub2 (using my own ISO with `loopback.cfg` neither using the Ubuntu one). Also I noticed that Fedora, Debian and Mageia live ISOs also do not include the loopback.cfg. I wonder if there is really a consensus about how this `loopback.cfg` should look like or should be used.

I'd like to avoid distro specific stuff. Do you have any hint about where to look for docs? Or could you enlight me about the smoke test I should do?

**Comment by probonopd** [comment]
I think this describes the standard: http://www.supergrubdisk.org/wiki/loopback.cfg

Here is related discussion in a Debian Bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757883

> I'd like to avoid distro specific stuff. 

Me too.

**Comment by Conan-Kudo** [comment]
I've never heard of this before. Nor am I sure there's any benefit to it. I maintain some of the Fedora Live Media creation tools, and I know we don't make these. So I wouldn't count this as cross distro...

**Comment by davidcassany** [comment]
@probonopd I don't think we should add it as something generic, thus for now I think it is just better to not include it. I see that `/usr/share/doc/packages/grub2/autoiso.cfg` provided in grub2 package is treated just as a documentation example and I could not manage to get it working with Ubuntu images (those include the `loopback.cfg` file). Also the Debian bug did not get much attention and after more than two years, `loopback.cfg` issue is still in the wishlist.

However, it is already possible to build ISOs with the `loopback.cfg` file. You can use the `config-cdroot.tar*` file (valid since #744) in order to include it (actually this is how I have been trying to get it working with the `autoiso.cfg`). Also you can find some hints about what to include there in #585.

Closing the issue since it is already possible to create images with the `loopback.cfg` config file and it doesn't look like something being widely adopted or standardized.

**Comment by probonopd** [comment]
> Closing the issue since it is already possible to create images with the loopback.cfg config file and it doesn't look like something being widely adopted or standardized.

Who (and in which bugtracker) would I have to convince to get loopback.cfg on the official openSUSE Leap and Tumbleweed Live ISOs?

**Comment by davidcassany** [comment]
@Vogtinator or @DimStar77, do you have an idea where feature requests for Leap and Tumbleweed Live ISOs should be submitted? 

@probonopd would like to see openSUSE images using the `loopback.cfg` file as other distros do to facilitate the boot of ISOs as a loopback device in Grub.

**Comment by DimStar77** [comment]
@davidcassany https://bugzilla.opensuse.org - Relevant Distribution, Component Live Image;

**Comment by Vogtinator** [comment]
This modifies the grub config, which is not feasible to do outside of kiwi.

It should be trivial to apply http://git.grml.org/?p=grml-live.git;a=blobdiff;f=templates/boot/grub/grub.cfg;h=31545bd0042dd1e62ed9f83ae81b85565881969b;hp=7e115d6044f0ff86e1944f3bf8121289ef67955b;hb=641c1ace68b52313653478ba4699ca46a1e84184;hpb=2fb103a7c7d8cc2aed11c42e1d29c273c7848049 to kiwi and thus make the grub.cfg of all built images compatible with loopback.cfg.

**Comment by probonopd** [comment]
How would we go about getting this going @Vogtinator?

**Comment by Conan-Kudo** [comment]
@probonopd You haven't yet convinced _me_ or anyone else in the kiwi team that this is worth implementing. By @davidcassany's own investigation, literally nobody is shipping the file.

**Comment by probonopd** [comment]
Ubuntu and its derivatives are all shipping it. It's a tiny text file, it would certainly not hurt anyone to ship it. Do you see any downsides?
