### ISSUE TITLE
Support setting %_install_langs in the config.xml

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE/kiwi#771]
## Problem description
I'd like for RPM to be configured with specific `%_install_langs` settings through the entire image build to minimize stuff being installed in the image.

This is especially necessary on target systems that don't have split langpacks and stuff like that, such as CentOS/RHEL, Mageia, and older openSUSE.

## Expected behavior
Some tag, like `<rpm-install-langs>` (similar to the other `rpm-*` tags), would let me set the value of `%_install_langs` to be used, like `C:C.UTF-8:en:en_US:en_US.UTF-8`

This would effectively do something like this:
`echo "%_install_langs C:C.UTF-8:en:en_US:en_US.UTF-8" > $CHROOT/etc/rpm/macros.d/macros.kiwi-langs`

## OS and Software information
+ KIWI version: 9.16.0
+ Operating system: Fedora 28
+ OBS version: N/A

**Comment by davidcassany** [comment]
@Conan-Kudo looks like a reasonable feature, just wondering if there is something similar for DEB packages or APT manager (I'd like to avoid further `rpm-*` tags in the schema), I did not find anything at a glance, are you aware of something similar? Also would be nice to handle that at package manager level, at zypper, dnf and yum configuration and avoid playing around with RPM macros.

**Comment by Conan-Kudo** [comment]
Unfortunately, this is an RPM specific feature, and while YUM has a config option for it, none of the others do.

@dmach Any chance of seeing the YUM option ported to DNF?

**Comment by davidcassany** [comment]
I have been thinking and looking at it again and I don't think we achieve it in any reasonable way. This is a similar problem we had with #133 for yum, the only way of doing it is using rpm macro files. The problem I see here is that for the bootstrap phase the macros used and the package manger used is the one installed within the host, thus in order to get that feature during the bootstrap phase (which I consider a must) we need to modify the host system macros. Of course we won't be hacking host system wide configuration files, too bad.

I could not find a way to define for zypper, yum or dnf a custom rpm macro file location. If we could create runtime macro files and make the package managers make use of it for the bootstrap phase that would be enough. 

So, currently, it seams this feature can only be implemented with YUM and I'd say this is not enough for us to implement it. Don't get me wrong, I understand that YUM will be replaced by DNF at some point, thus adding specific code for YUM does not have much sense IMHO.

@Conan-Kudo, @schaefi any further thoughts?

**Comment by dmach** [comment]
@Conan-Kudo I think we could implement it in libdnf.
Could you open a bugzilla and describe the behavior incl. chroot use case?
Correct chroot handling is a key, because I expect this to be used for image building, chroot installs etc.

**Comment by schaefi** [comment]
> ...thus in order to get that feature during the bootstrap phase (which I consider a must) we need to
> modify the host system macros.

yeah this is not a route we can go

I think it can only be set by us if the package manager provides an option which makes the setting active in rpm for the call time

**Comment by Conan-Kudo** [comment]
@dmach, @davidcassany, @schaefi: Bug filed: https://bugzilla.redhat.com/show_bug.cgi?id=1610757

@dmach: Is there any more information you need in there?

**Comment by schaefi** [comment]
The bug is still in state ```new``` which I guess means that currently no resources are set on it. I'll set this issue to be blocked on the result of the bug as I think we can't start an implementation as long as the support in dnf is not present. As I don't have a look on a regular basis on the rhel bug system it would be great if you guys drop us a note when something has changed. Thanks

**Comment by davidcassany** [comment]
@schaefi, yes for yum we can start adding it. Also we could open a request for that in zypper and see.

**Comment by schaefi** [comment]
Ok we are finally in a position to fix the issue reported here. So I did some checks on the macro side.
By default I get:

```
$ rpm -E %_install_langs

all
```

I guess we want to specify a subset or only one language. Now my question is:

* what values are expected/allowed ?

In the kiwi XML description we already have the element:

```xml
<preferences>
    <locale>en_US,de_DE</locale>
```

to specify a list of locale names. The kiwi schema only allows this format:
locale-name = xsd:token {pattern = "(POSIX|[a-z]{2,3}_[A-Z]{2})(,[a-z]{2,3}_[A-Z]{2})*"}

So could that information be used here. I would say yes

@Conan-Kudo question goes basically to you

Thanks

**Comment by Conan-Kudo** [comment]
That should work, but it's a colon separated list...

**Comment by schaefi** [comment]
> That should work, but it's a colon separated list...

Uh, colon... then we can't do it ;) nah just kidding. Ok I'll jump on this on the next free slot. I'm happy that we can solve it in a good way now
