### ISSUE TITLE
Unable to build CenOS image in OBS

### ISSUE THREAD

**Issue by pda14** [SUSE/kiwi#785]
## Problem description
There's description of a problem https://lists.opensuse.org/opensuse-buildservice/2018-07/msg00051.html and closed issue report on obs github https://github.com/openSUSE/open-build-service/issues/5360
Something wrong with package's(missing kiwi-image-iso-requires for CentOS?). 

## Steps to reproduce the behaviour
1. Create new project in OBS, create package, add repositories to build against(including kiwi).
    <repository name="images"> <path project="openSUSE.org:Virtualization:Appliances:Builder" repository="CentOS_7"/> <path project="openSUSE.org:CentOS:CentOS-7" repository="standard"/> <arch>x86_64</arch> </repository>
2. Add centos-07.0-JeOS.kiwi to package, replace default repository entries with "source path="obsrepositories:/"". Comment out unneeded image types. Choose iso image type.
3. See error nothing provides kiwi-image:iso

## OS and Software information
+ KIWI version:  python3-kiwi-9.16.2-106.1
+ Operating system: OBS host on openSUSE Leap 42.3
+ OBS version: 2.9.3

**Comment by davidcassany** [comment]
in order to solve the `kiwi-image:iso` dependency you can configure the OBS project configuration as we do in our Fedora test [here](https://build.opensuse.org/project/prjconf/Virtualization:Appliances:Images:Testing_x86), see the line with

```
substitute: kiwi-image:vmx python3-kiwi
```
This actually tells OBS to provide `kiwi-image:vmx` with python3-kiwi. For CentOS you can try to do something like

```
substitute: kiwi-image:iso python2-kiwi
```

as there is no python3-kiwi in our centos repo.

I tried that and run with some other issues related to specific CentOS dependencies which I am currently having a look at. However, the above solves your inital issue. This happens mostly because there is no build for CentOS and other non SUSE distros of ` kiwi-image-iso-requires.rpm` and similar packages. Those packages are only metapackages requiring some tools specific for the image type, this mostly used within SUSE's workflows.

**Comment by pda14** [comment]
Thanks! I will try that.

**Comment by pda14** [comment]
Yes. kiwi-image:iso issue fixed. But that substitute trick doesn't work for me in case of python-PyYAML and python-xattr:
"nothing provides python-PyYAML needed by python2-kiwi, nothing provides python-xattr needed by python2-kiwi"

Substitute: python-xattr pyxattr
Substitute: python-PyYAML PyYAML

**Comment by davidcassany** [comment]
@Conan-kudo thanks for looking at it, if fact i realized the pyyaml requirement should be modified to be centos compatible.

I am a bit confused by the patch related to `pyxattr`, shouldn't it be enough updating spec to require `pyxattr` in `rhel` or `rhel < 8`?

**Comment by Conan-Kudo** [comment]
@davidcassany No, because `/usr/bin/kiwi` actually checks for the module to be installed (it's wired into setuptools), and if it isn't, it crashes.

**Comment by davidcassany** [comment]
@Conan-Kudo, thanks I see, I was not aware that pyxattr and xattr were two different implementations... it confused me

**Comment by davidcassany** [comment]
@pda14 I managed to build a CentOS image in OBS with a small change in python2-kiwi spec, see #786. You can use [this project](https://build.opensuse.org/package/show/home:dcassany:branches:Virtualization:Appliances:Images:Testing_x86/test-image-centos-vmx) I did as a reference, note that  `python-xattr` is not present in CentOS and required by KIWI, in my example this package is build [here](https://build.opensuse.org/project/show/Virtualization:Appliances:Staging).

@Conan-Kudo I realized that `pyxattr` is provided by `python-xattr` package in openSUSE, thus moving to `pyxattr` python module does no look like a good move as our code is only tested against the `xattr` python module.
