### ISSUE TITLE
no docs for creating vagrant boxes

### ISSUE THREAD

**Issue by aspiers** [SUSE/kiwi#792]
AFAIK, creation of vagrant-libvirt boxes is supported (we're even using it), but it is not documented at https://suse.github.io/kiwi/index.html

I saw #532 which says that the next generation kiwi lacks support for the virtualbox provider of vagrant box images.  So this should be documented too, especially since this is a regression from the previous generation of kiwi.

Without documentation on this, we will see [people continuing to try to build openSUSE images outside OBS using Packer](https://github.com/openSUSE/vagrant/issues/11), and I'm not sure that's an optimal situation.

**Comment by schaefi** [comment]
yes I agree we should write how to do it and also to what extend it's supported. With #532 I had hoped to find an easy solution but having no ovf writer at hand for the virtualbox target is a show stopper here because again maintaining our own ovf writer will end up in the same broken code as we have it in the previous generation. I'm sure we'll find a better working solution in this regard, until then I agree with you it's a regression or let's better say "not yet ported" :)

Thanks
