### ISSUE TITLE
SquashFS as rootfs over HTTP needs livenet support

### ISSUE THREAD

**Issue by Jamesits** [SUSE/kiwi#827]
## Problem description
I'm trying to build an openSUSE JeOS image for PXE boot. The environment requires layer-3 file transfer so AoE is not possible. The dracut manpage said it supports mounting squashfs via HTTP, but it seems impossible with a kiwi-built image.

I used the example openSUSE JeOS 15.0 config to generate an ISO. Then I extracted the ISO and got the kernel, initrd and the rootfs. After that I used the following script to boot via iPXE.

```shell
#!ipxe

kernel http://server/linux rd.live.debug=1 rd.live.image rd.shell root=live:http://server/squashfs.img
initrd http://server/initrd
boot
```

The kernel and the initrd works, but when it is mounting the rootfs, the dmesg says:
```
loop: module loaded
dracut: FATAL: Don't know how to handle 'root=live:http://server/squashfs.img'
dracut: Refusing to continue
```

Then the kernel shuts down.

I've tried other package types, like `squashfs` and `oem`, they seems to have this problem too. 

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.15.3
+ Operating system: openSUSE Leap 15.0
+ OBS version: N/A

**Comment by schaefi** [comment]
> I'm trying to build an openSUSE JeOS image for PXE boot. The environment requires layer-3 file
> transfer so AoE is not possible. The dracut manpage said it supports mounting squashfs via HTTP, 
> but it seems impossible with a kiwi-built image.

You would need to switch to the upstream dracut dmsquash-live module which you can do with the following additional attribute in your type line

```xml
<type .... flags="dmsquash"/>
```

if the iso is built that way the dracut module should understand your root=live:http... setup

I'm closing for now, feel free to re-open if there is still a problem in the scope of kiwi

Thanks

**Comment by Jamesits** [comment]
@schaefi Thanks for your patience.

I changed to the following type definition:

```xml
<type image="iso" flags="dmsquash" hybrid="true" firmware="efi" hybridpersistent_filesystem="ext4" hybridpersistent="false"/>
```

But I still gets the same error. Am I doing something wrong?

**Comment by schaefi** [comment]
So the good news is that the livenet code is active and does something. The dracut code to setup the network via dhcp is on suse systems a modified module using wicked. You can see that in the log and it also seems that dhcp setup worked because I also can see the typical curl line trying to download data.
It also seems to mount that downloaded squashfs image but after that you are stuck in the init queue.

First you should eliminate that something is wrong with the download or the image. So can you check the following from some machine in this network:

* curl http://server/output/LiveOS/squashfs.img
* mount squashfs.img /mnt

If this works I suggest to run the pxe boot again with ```rd.debug```, depending on where the loop begins you will end up in a rescue shell which allows for further debugging. In any case you get a lot more information on the console though.

If there is no interactive shell reboot again with ```rd.debug rd.break=initqueue```

From there you can further debug or contact the developers of the livenet code for help

As the original issue in the scope of kiwi is fixed this issue will be closed once the pull request gets merged. Please re-open if you find further issues which we can solve in kiwi.

Hope this helps
