### ISSUE TITLE
Building fails with non-C locale

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#829]
Building an image with `LANG=de_DE.UTF-8` fails:

```
[ DEBUG   ]: 23:25:45 | EXEC: [mkdir -p /root/output/build]
[ INFO    ]: 23:25:45 | Loading XML description
[ INFO    ]: 23:25:45 | --> loaded /usr/share/kiwi/image/suse-SLE12-Enterprise-JeOS/JeOS.kiwi
[ INFO    ]: 23:25:45 | --> Selected build type: vmx
[ INFO    ]: 23:25:45 | --> Selected profiles: kvm-and-xen
[ INFO    ]: 23:25:45 | Preparing new root system
[ INFO    ]: 23:25:45 | Setup root directory: /root/output/build/image-root
[ DEBUG   ]: 23:25:45 | EXEC: [mkdir -p /root/output/build/image-root]
[ DEBUG   ]: 23:25:45 | EXEC: [cp /var/adm/fillup-templates/group.aaa_base /tmp/kiwi_root.oGROOs/etc/group]
[ DEBUG   ]: 23:25:45 | EXEC: [cp /var/adm/fillup-templates/passwd.aaa_base /tmp/kiwi_root.oGROOs/etc/passwd]
[ DEBUG   ]: 23:25:45 | EXEC: [cp /var/adm/fillup-templates/sysconfig.proxy /tmp/kiwi_root.oGROOs/etc/sysconfig/proxy]
[ DEBUG   ]: 23:25:45 | EXEC: [rsync -a --ignore-existing /tmp/kiwi_root.oGROOs/ /root/output/build/image-root]
[ DEBUG   ]: 23:25:45 | EXEC: [cp /etc/resolv.conf /root/output/build/image-root/etc/resolv.conf.kiwi]
[ DEBUG   ]: 23:25:45 | EXEC: [ln -s -f resolv.conf.kiwi /root/output/build/image-root/etc/resolv.conf]
[ DEBUG   ]: 23:25:45 | EXEC: [cp /etc/hosts /root/output/build/image-root/etc/hosts.kiwi]
[ DEBUG   ]: 23:25:45 | EXEC: [ln -s -f hosts.kiwi /root/output/build/image-root/etc/hosts]
[ DEBUG   ]: 23:25:45 | EXEC: [cp /etc/sysconfig/proxy /root/output/build/image-root/etc/sysconfig/proxy.kiwi]
[ DEBUG   ]: 23:25:45 | EXEC: [ln -s -f proxy.kiwi /root/output/build/image-root/etc/sysconfig/proxy]
[ DEBUG   ]: 23:25:45 | EXEC: [mountpoint /root/output/build/image-root/proc]
[ DEBUG   ]: 23:25:45 | EXEC: [rm -f /root/output/build/image-root/etc/resolv.conf.kiwi /root/output/build/image-root/etc/hosts.kiwi /root/output/build/image-root/etc/sysconfig/proxy.kiwi /root/output/build/image-root/etc/resolv.conf /root/output/build/image-root/etc/hosts /root/output/build/image-root/etc/sysconfig/proxy]
[ ERROR   ]: 23:25:45 | KiwiMountKernelFileSystemsError: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 48: ordinal not in range(128)
[ INFO    ]: 23:25:45 | Cleaning up SystemPrepare instance
```

**Comment by davidcassany** [comment]
> Building an image with LANG=de_DE.UTF-8 fails

I assume this was with `<locale>de_DE</locale>`, right? I could not reproduce this issue on my Leap 15 neither on my SLE-12-SP3 or SLE-15 hosts. Which was your host distro and kiwi version?
Or it is the build host that is set to `de_DE.UTF-8`?

It happened calling `python2-kiwi` or `python3-kiwi?` I have seen this `unicodeDecodeError` message when some command returns to `stdout` or `stderr` non `ascii` characters, it only happens in python2. Since it is likely to be a `stderr` message I guess in `python3-kiwi` might also fail, but probably with a more understandable error message. 

This python2 decoding issue is not nice and I doubt we can do much about that. At most we could assume that python2 always uses utf-8 and force it, but then we would also find some other corner cases that would fail when non utf-8 characters are used by some tool.

**Comment by Vogtinator** [comment]
> I assume this was with <locale>de_DE</locale>, right? I could not reproduce this issue on my Leap 15 neither on my SLE-12-SP3 or SLE-15 hosts. Which was your host distro and kiwi version?
Or it is the build host that is set to de_DE.UTF-8?

The build host is a SLE 12 SP4 and has a German locale. The kiwi file has `<locale>en_US</locale>`. With `LANG=C.UTF-8` it works.

> It happened calling python2-kiwi or python3-kiwi?

python2-kiwi (unfortunately).

**Comment by schaefi** [comment]
yes this is the "classic unicode" problem which is more of a problem in py2 than in py3. In py3 a string is always a unicode string and the str type is bytes. In py2 the default encoding is ascii and any string is of this type if not explicitly encoded differently. A decode() from a unicode string solves many of these problems but not all.

In this case the data comes through a pipe from a command called from the de_DE.UTF-8 locale. In py3 that are bytes which gets decoded to the system locale, thus no problem. In py2 we use from future bytes but they are decoded using ascii which causes the UnicodeDecodeError you saw.

The real fix should go into py2 but that will never happen so the python developers decided to really fix all of that in py3 introducing real bytes type and unicode internally by default. That leaves us who tries to support both worlds in one code base with the problem how to handle it. The only solution I had in the past was to force utf-8 in decode() or force sys.setdefaultencoding('utf8'). Both are poor solution and have several bad aftereffects which you can read all over the net (stackoverflow and friends)

Thus our decision with respect that py2 will go away and that we can control the locale the application is started in very easily is to not force any encoding.

I'm afraid but if you stick with python2-kiwi I suggest to write a small shell wrapper which sets the locale to C like I did it in the build script of obs when I added image build support in the workers.

Hope that makes sense

Thanks

**Comment by Vogtinator** [comment]
> I'm afraid but if you stick with python2-kiwi

I'm afraid that's not my decision, SLE 12 only ships python2-kiwi.

Please talk to PM/RM, this seems like a convincing argument.

**Comment by davidcassany** [comment]
I am reopening since I noticed this specific failure has a simple fix. This in this case the offending call is `mountpoint <path>` which returns some sort of message with the selected language. However KIWI does not parse that, it only check for the return code. I checked `mountpoint` and it has `-q` flag for quiet output that solved this specific issue. Gonna prepare a PR for that.

@schaefi in addition to the above I have been thinking that it would make sense trying to catch those specific errors in a certain custom Exception in `command.py`. I noted we do not try/catch the `output.decode()` call. Handling this exception should help us produce nicer error failures, at least to know the exact command that created this error and if the command itself failed or not. 

Thoughts?

**Comment by schaefi** [comment]
Well ok, calling mountpoint to not say anything is a nice workaround and makes sense to me

catching the UnicodeDecodeError is an option if you try to run decode('utf-8') and see if that provides a message. If you still can't decode we can end with an error message saying that the locale setup of the system is "not utf-8 compatible".

To be honest trying to be clever here is not the road to success. I avoided decode() as much as possible but there are two places where it is needed:

* ./command.py and ./command_process.py
* ./iso_tools/iso.py

You are trying to catch the first in the list and that fortunately covers almost all of it, so I'm ok with that.
For completeness the iso code chaning the header bits should also be covered. Fortunately that will go away with xorriso, but it does not exists on sle12, so should be part of a patch if you want to address it

If at any time in the future a further decode() is needed we have to remember the workarounds. Thus I also suggest to create our own private and code global decode which does that two phase system if the first decode raises.

If we take all that into account I'm ok with patching

Thoughts

**Comment by davidcassany** [comment]
Ok, I did not saw the decode in `iso_tools/iso.py` and I had just started having a look to `command_process.py`. 

Creating our own decoding utility to handle this failures looks like the way to go IMHO. We could add a `utils/decode.py` with a classmethod to perform this two steps decoding in case of failures. Then in should cover most of decoding issues of python2.

**Comment by brejoc** [comment]
Could it be, that we are seeing this due to the removal of `<locale>de_DE</locale>` in Leap 15.0?

```
$ localectl status
   System Locale: n/a
       VC Keymap: n/a
      X11 Layout: n/a
```

The System Locale is set to `n/a`, which seems to cause weird problems (namely UnicodeDecodeErrors) with some (Python) applications. `LANG` and `LANG_XXX` all seem to be set to `C.UTF-8` on the other hand, which also limits us a little bit:

> C.utf8 = POSIX standards-compliant locale, extended to allow the basic use of UTF-8. No character upper-lower case relationships and collation orders defined beyond ASCII.
