### ISSUE TITLE
/etc/machine-id preset in image

### ISSUE THREAD

**Issue by azouhr** [SUSE/kiwi#843]
## Problem description  
The file /etc/machine-id is preset in readily built images. This results in all deployments of images, the machine-id is identical although this should be a unique setting.

## Expected behaviour
Just add an empty file /etc/machine-id to the images. This makes systemd generating a new id during first startup.

## Steps to reproduce the behaviour
Build an image and deploy it several times. The content of /etc/machine-id should be different.

## OS and Software information
+ KIWI version: 9.16.?
+ Operating system: all with systemd
+ OBS version: -

**Comment by schaefi** [comment]
To my knowledge  /etc/machine-id is provided with the systemd package. Meaning it comes with the packages and is not actively created by kiwi. As you already found out deleting it or empty it out as part of the ```images.sh``` script triggers dracut to create a new one on boot.

I'm unsure what you suggesting, should kiwi actively delete/empty the file ?

I think this is something we should not do because the integrity of the system is then depending on boot code rebuilding systemd information. As this will work in almost all cases there are still scenarios where the system is set active without an initrd running beforehand, e.g containers

I would be interested on other peoples opinion

**Comment by azouhr** [comment]
My main interest is for golden images. I do not really look at containers, although I would have thought that with containers there would not be a systemd, and thus probably no machine-id.

The suggestion is to empty this file. This was the advice I got from the systemd people when I asked how to make sure that the machine-id is reset during installation of a golden image.

Of course, this should not be repeated after the system has started. However, journald and arbitrary other services might rely on different machine-id settings on different machines.

**Comment by schaefi** [comment]
> I would have thought that with containers there would not be a systemd, and thus probably no machine-id.

For docker this is almost always the case but there are other ongoing container challenges with e.g the podman project which has systemd support as a main feature. My point here is that I can only add the machine-id setup as you mentioned as a preparation task for dracut.

I'll prepare the implementation, stay tuned :)

**Comment by davidcassany** [comment]
About this issue I remember we reverted the code to remove `/etc/machine-id` because it was triggering an interactive systemd session during firstboot, see https://github.com/SUSE/kiwi/commit/e612e4e5cf5e1c04b30853c69eb07af5b4bf0445.

Also because of that we added this [tip](https://opensource.suse.com/kiwi/overview/workflow.html#configuration-tips) in docs. IIRC we opted to keep this sort of machine ID changes out of our code base because it was unclear to have a common behavior with all supported distros.

Just to add some background and my 2 cents

**Comment by schaefi** [comment]
Oh yes you are right I remember that. The pull request I opened just empties the file and as it seems this advise came from the systemd maintainers I thought it might be safe.

But yes we should clarify this first

> This was the advice I got from the systemd people 

@azouhr: Could you share your systemd contact or head out to the people you asked and let us know if Davids concern is still valid ? Thanks

**Comment by azouhr** [comment]
It's some time ago that I had this issue. But as far as I remember, I got this advice from Lennart Poettering on some systemd mailing list. The desired behavior is actually documented at https://freedesktop.org/software/systemd/man/machine-id.html : 

>  For operating system images which are created once and used on multiple machines, for example for containers or in the cloud, /etc/machine-id should be an empty file in the generic file system image. An ID will be generated during boot and saved to this file if possible. Having an empty file in place is useful because it allows a temporary file to be bind-mounted over the real file, in case the image is used read-only.

**Comment by schaefi** [comment]
Thanks, that makes it pretty clear in my opinion.

@davidcassany I read the tip and there we also wrote to create an empty file because removing would lead to the interactive systemd-firstboot session. Thus I think it would be ok to let kiwi empty out the file for those cases where we know the dracut initrd will create a new id. That would be the open PR in #845

Next I checked the linkage between var/lib/dbus/machine-id and /etc/machine-id and found that this link is already present after the package installation. Thus our code snippet would be a valid approach only on older distributions, probably only on sle12 which I will check next.

If you are ok I'd like to follow the systemd documented approach in kiwi and also adapt the tip in a way that it:

* provide information what happens if one deletes etc/machine-id
* provide information to link var/lib/dbus/machine-id to etc/machine-id on systems where this is not already the case

Thoughts ?

**Comment by davidcassany** [comment]
@scheafi yes that makes sense. In fact I also noted that the change in the PR was pretty aligned with the findings we did a while ago about making the file empty instead of removing it. I added my comment just to make sure we had into consideration the findings and issues we had in past and also to somehow to trace all the information into the issue discussion (hopefully we won't have to read it again, but who knows...).

>    * provide information what happens if one deletes etc/machine-id
>   * provide information to link var/lib/dbus/machine-id to etc/machine-id on systems where this is not already the case

Fine for me, I can take care of it, I can prepare a docs PR.

**Comment by schaefi** [comment]
just checked on sle12 var/lib/dbus/machine-id and etc/machine-id are two different files but with the same content. I'd say that should stay as a doc topic

> Fine for me, I can take care of it, I can prepare a docs PR.

sounds good to me. I'll wait with the code merge. Thanks
