### ISSUE TITLE
Persistent usb does not work with opensuse

### ISSUE THREAD

**Issue by wandersfalsin** [SUSE/kiwi#860]
I'm trying to use the command "sudo live-grub-stick --suse-persistent ./openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20181018-Media.iso /dev/sdd1" to generate a persistent pendrive, but persistence is not working. Once the command in the grub "isofrom=" has been changed to "iso-scan/filename=" the persistence has not worked any more, this happens after the second half of 2017.

**Comment by schaefi** [comment]
Further details here:

https://github.com/SUSE/kiwi/issues/574#issuecomment-432700190

**Comment by schaefi** [comment]
Thanks for the log. So you used an USB stick which contains one primary partition that fills up all space of the stick. The call of the ```live-grub-stick``` tool placed the image file and the grub setup and the bootloader data on the stick in that partition. Now when you boot from the stick the dracut kiwi code tries to prepare a write space for the persistent writing on that stick and failed because there is no space left to create another partition:

```
/run/rootfsbase

Welcome to fdisk (util-linux 2.32.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Command (m for help): All space for primary partitions is in use.

Command (m for help): Disk /dev/sdb: 7.5 GiB, 8053063680 bytes, 15728640 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xfcb7fd71

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1  *     2048 15728639 15726592  7.5G 83 Linux
```

See the __All space for primary partitions is in use__ message ? That's why in the end the fallback to temporary writing applied.

So there is plenty of space available on the stick but none to create an extra write partition which is the concept behind persistent writing. To make that work you would need to keep some space free on the stick. As this is unusual and I guess the majority have sticks which just have this setup with one big partition I think we could enhance the concept and allow a persitent write file instead of a partition.

I'll look into that on a free slot

**Comment by wandersfalsin** [comment]
I did a test using an empty partition and during boot the system creates a partition with the label "cow" for persistence. But if the "cow" partition is already created it will use it without overwriting. It worked after removing the kiwi_cowdevice and kiwi_cowsystem parameters from grub. This is the big problem, not being able to set other places for the cow drive.


[boot.kiwi2.txt](https://github.com/SUSE/kiwi/files/2516002/boot.kiwi2.txt)
