### ISSUE TITLE
Non-rootfs image builds are broken

### ISSUE THREAD

**Issue by ggardet** [SUSE/kiwi#935]
## Problem description
Non-rootfs images fail with the following error:
```
[  510s] [ INFO    ]: 00:59:21 | --> Creating unsigned efi image
[  510s] [ ERROR   ]: 00:59:21 | KiwiBootLoaderGrubDataError: No grub2 installation found in /usr/src/packages/KIWI-oem/build/image-root/usr/lib
[  510s] [ INFO    ]: 00:59:21 | Cleaning up BootImageDracut instance
[  510s] [ INFO    ]: 00:59:21 | Cleaning up Disk instance
```

## Expected behaviour
Images should build fine, as previously.

## Steps to reproduce the behaviour
Check failure list from: https://build.opensuse.org/project/show/openSUSE:Factory:ARM:Live

## OS and Software information
+ KIWI version: python3-kiwi-9.17.1-2.2
+ Operating system: openSUSE Tumbleweed ARM (aarch64, armv6/7)
+ OBS version: build.o.o

**Comment by schaefi** [comment]
The change in the grub package has caused all this. See fate#326960 if you have access to that feature tracking system. Other than that it was all fixed with the PR from the issue report in #924

The kiwi version you are using to build just doesn't have this Fix. I have submitted latest kiwi for Factory but probably arm is late. Feel free to use the Virtualization:Appliances:Builder project from obs it builds against openSUSE_Factory_ARM too
