### ISSUE TITLE
<ignore name="foo"/> does not work for profiles

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/kiwi#941]
When building the `kubeadm-cri-o-kvm-and-xen` profile for a description such as

```
  <profiles>
        <profile name="kubeadm" description="kubeadm"/>
        <profile name="cri-o" description="CRI-O"/>
        <profile name="kubeadm-cri-o-kvm-and-xen" description="kubeadm with CRI-O for KVM and HVM Xen" arch="x86_64">
            <requires profile="kvm-and-xen-x86_64"/>
            <requires profile="kubeadm"/>
            <requires profile="cri-o"/>
        </profile>
       ...
  </profiles>
    <packages type="image" profiles="cri-o">
        <package name="podman-cni-config"/>
        ...
    </packages>
    <packages type="image" profiles="kubeadm">
        <package name="cri-o-kubeadm-criconfig"/>
        <ignore name="podman-cni-config"/>
        ...
    </packages>
```

it still tries to install the `podman-cni-config` package even though it's ignored.

**Comment by davidcassany** [comment]
I do not understand the posted xml sources. It requests  `cri-o-kubeadm-criconfig` and adds ignore to the same package into the same profile. I guess there is a mistake here.

If the ignore was `podman-cni-config` then the profile `kubeadm-cri-o-kvm-and-xen` is not really consistent as KIWI first sets the zypper lock (ignore) and then installs required packages. Thus adding a lock before installing and then require its installation will always fail.

`<ignore>` makes sense if you are using the `patternType="plusRecommended"` attribure of `<packages>` otherwise it is hard to find a case where it is useful, probably if something is provided by multiple packages and that's all.

**Comment by Vogtinator** [comment]
> I do not understand the posted xml sources. It requests `cri-o-kubeadm-criconfig` and adds ignore to the same package into the same profile. I guess there is a mistake here.

Indeed, fixed now.

> `<ignore>` makes sense if you are using the `patternType="plusRecommended"` attribure of `<packages>` otherwise it is hard to find a case where it is useful, probably if something is provided by multiple packages and that's all.

Which is the case here - cri-o-kubeadm-criconfig and podman-cni-config conflict, so the matching one needs to be installed.

The only way this could be handled in a kiwi description without handling `<ignore/>` this way is by adding a new profile with just `podman-cni-config` and add that profile to all non-kubeadm profiles. That does not scale.

Previously there was `<package name="cri-o-kubeadm-criconfig" replaces="podman-cni-config"/>` which might've been more what's needed here, but it's now gone from kiwi so I don't even know what it did when it still existed.

**Comment by davidcassany** [comment]
> Which is the case here - cri-o-kubeadm-criconfig and podman-cni-config conflict, so the matching one needs to be installed

Well, they conflict but do not provide equivalent functionality. They do not share any `provides`. I am not aware of the functionality of the cni config and why is it incompatible with the kubernetes kubelet, but if `kubeadm-criconfig` is providing a CNI config that probably could include a `Provides: cni-config` and also include that in `podman-cni-config`. Then you would just require `<package name="cni-config">` in cri-o profile.

Those two packages conflict, thus there shouldn't be a profile trying to install both of them.

> The only way this could be handled in a kiwi description without handling <ignore/> this way is by adding a new profile with just podman-cni-config and add that profile to all non-kubeadm profiles. That does not scale.

I'd say this is the correct solution. If profiles turn to be unmaintainable within the description file this might be a symptom that probably this description is trying to cover too many images in a single file.

> Previously there was `<package name="cri-o-kubeadm-criconfig" replaces="podman-cni-config"/>` which might've been more what's needed here

Up to my knowledge this was not ported to kiwi-ng. I doubt this was just forgotten, I am pretty sure it was done on purpose just to enforce more explicit definitions. A common use case for it was setting different kernels based on profile, which IIRC was potentially causing issues with the custom initrd's and making them hard to debug.

**Comment by schaefi** [comment]
correct the replaces definition was intentionally not ported to enforce explicit definitions. In the beginning I thought it was a good idea to support that on the image description level but it has turned out to be a bad idea. If "kubeadm-criconfig" is a replacement for "podman-cni-config" this should be usually expressed on the package level with obsoletes/provides. If there is no relation and the package or the other depends on an image detail it should be expressed in profiled packages sections, which is also supported by obs in multibuild configurations if I remember correctly. The later would explicitly create a statement why this is done which is hidden in a replaces attribute

> I'd say this is the correct solution. If profiles turn to be unmaintainable within the description file this
> might be a symptom that probably this description is trying to cover too many images in a single file.

 I fully agree

**Comment by Conan-Kudo** [comment]
@Vogtinator Have you considered changing the packages to have some rich dependencies so that the correct thing is requested? This really seems like that would be the right solution here.

Also, CNI implies it is a standard setup, so there's no reason they wouldn't have some kind of useful Provides here for swapping between the two...?

**Comment by Vogtinator** [comment]
> @Vogtinator Have you considered changing the packages to have some rich dependencies so that the correct thing is requested? This really seems like that would be the right solution here.

Package changes are unfortunately not in my control here.

The profile restructuring made it possible to avoid this issue luckily.
