### ISSUE TITLE
[Enhancement] Add Jenkins pipeline to the CI?

### ISSUE THREAD

**Issue by dcermak** [SUSE/kiwi#960]
## Problem description

Kiwi's test coverage is absolutely outstanding! Nevertheless, the unit tests rely on the developer testing their local changes first and then create appropriate unit tests. This unfortunately still leaves the possibility that kiwi's tests pass, but a regression is introduced during refactoring. E.g. a config file is changed in an a way that looks safe but isn't and results in some images not building or they build but will not boot, etc.

### Possible solutions

1. Provide a procedure for manual testing. This could be a script that will build various images, tries to boot them and maybe execute a script on these. But, this will probably be overkill for most changes and depending on the type of machine contributors have access to, this will take hours to finish.

2. Automate the test, for example via Jenkins. There appear to even exist some pipelines for kiwi on ci.opensuse.org, but they have not been used for a year: https://ci.opensuse.org/view/kiwi/ci.opensuse.org. How about we resurrect these and/or add new ones?

**Comment by schaefi** [comment]
I fully agree unit test never replace good integration testing

However we already have an integration test process in place. If you look at:

* https://opensource.suse.com/kiwi/

In the right box with the link list. You see the links to our integration test build matrix for several architectures. If I pick x86 it's this link

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_x86

All the image test builds here starts whenever something changes on the distro level as well as if we submit a new kiwi package to the staging area here:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Staging

Only if the test builds are green we submit the package to the builder:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Builder

The matrix for test builds can always be better and I'm not satisfied with the coverage but I like the process we have established here. Currently I don't see a reason for Jenkins which is also the reason why the existing tests there are more or less meaningless.

The reasons why I think the integration testing should be done in the buildservice are:

* It's open and can be used for the opensource effort too
* all suse products based on images are built in the buildservice
* all major distros rhel, fedora, ubuntu, suse ... exists as target in the buildservice and are tested by us

So currently I rather would like to extend the existing pipeline instead of investing more on Jenkins.
Hope that makes sense to you too

**Comment by dcermak** [comment]
I am aware of the builds, the only problem I see (especially with respect to vagrant boxes) is that you can successfully build a broken image, that will error once you perform a `vagrant up`. That is something that Jenkins could catch but OBS can't.

**Comment by schaefi** [comment]
For the end-to-end testing including a boot of the image we use https://kanku.suse.de/kanku/ that is connected to the buildservice. I think it would be possible to run vagrant here as well. Maybe you ask ```Frank Schreiner fschreiner@suse.de``` if it's possible to create a job that does this.

You are right with Jenkins being able to test build results. The problem is imho the trigger if new build results are available you need to run the jenkins job. This interconnection between the services is something I always missed and had to be done by us in the past. With the kanku service we get this for free.

Also in Jenkins I need to care for my machines. The machine to run the jobs must be also setup by us. Also the architecture differences would require at least one machine per arch, that is x86_64, s390 and arm.

I agree with you all of that can be done with Jenkins but setting up and maintaining the infrastructure is quite some work and persists as extra work as long as it runs. I did not invest into this concept since we are very limited on resources for kiwi anyway.

If people are interested to create that testing infrastructure it would be nice but I think we should first check if not already existing services could be re-used. If we go the jenkins route I also suggest to use machines in the public cloud and do not host them in our data center

**Comment by dcermak** [comment]
> For the end-to-end testing including a boot of the image we use https://kanku.suse.de/kanku/ that is connected to the buildservice. I think it would be possible to run vagrant here as well. Maybe you ask Frank Schreiner fschreiner@suse.de if it's possible to create a job that does this.

I'll take a look at that. This actually is 99% of what I wanted (the remaining 1% would be a feedback on Github whether this PR breaks something).

Concerning jenkins: I am aware of all the problems with it including hosting etc. I suggested Jenkins, since I simply didn't know kanku existed. The only advantage Jenkins could have over that solution, is that Jenkins can be connected to GitHub and provide feedback on pull requests directly (but that would require that the Jenkins workers build the images themselves, which opens another can of worms). So: let's not use Jenkins for now.

Thanks for your time answering my question!
