### ISSUE TITLE
kiwi initrd does not configure DASD on Z Systems (missing tools)

### ISSUE THREAD

**Issue by azouhr** [SUSE/kiwi#963]
## Problem description
When trying to build an image for s390x, the image boots but then fails to configure its main CKD Disks (DASD). I found that this is due to two missing tools that are needed by `dasd_configure`, `getopt`, and `chzdev`

After adding these two tools to `kiwi/config/strip.xml`, the bootup worked:
```
   <strip type="tools">
        ....
        <file name="getopt"/>
        <file name="chzdev"/>
        ....
   </strip>
```
## Expected behaviour
System should find its boot disk to start firstboot configuration.

## Steps to reproduce the behaviour
* Build an OEM Image for s390x with DASD as disk device
* Try booting
* system will not boot because it is unable to detect its boot disk

## OS and Software information
+ KIWI version: python2-kiwi-8.33.14-9.29.11
+ Operating system: SLES12-SP3
+ OBS version: 

Note that in that KIWI version, the losetup is still broken ( losetup -L versus losetup --logical-blocksize); there fore it might be a good idea to also address this when updating the package for SLES. I can also open a support ticket if you wish.

**Comment by schaefi** [comment]
regarding the losetup see this: #d70d8d85cc03fa65b39f49

I stumbled across the same problem for s390 on Factory :)

**Comment by schaefi** [comment]
Regarding the issue I will update the strip.xml as you suggested. But I'd like to encourage you to switch to the dracut initrd_system using the latest kiwi version. For an example see:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_s390

The image build there fails for Factory but that's a problem of obs imho (either kernel issue or kpartx issue not mapping fdasd created partition tables). I do not expect this problem to exist on SLE, so just to give you an idea for the future because oemboot/... kiwi boot descriptions are only kept for legacy and compat reasons
