### ISSUE TITLE
No network interfaces found with PXE and DHCP

### ISSUE THREAD

**Issue by Maini12** [SUSE/kiwi#970]
## Problem description
  We built our PXE-image in OBS: [OBS](https://build.opensuse.org/package/show/home:Maini12:branches:home:AdaLovelace:linuxlaboratory/openSUSE-Leap-15.0)
Our tftp-Server sucessfully loads the kernel.
During loading the initrd we received the systemException No network interfaces found (see attached picture).
![img_20190227_114932](https://user-images.githubusercontent.com/7264826/53486109-23acc800-3a88-11e9-829a-0d24f094ca73.jpg)
Our clients are configured to boot in UEFI-Mode.
## Expected behaviour
Since this image is not a live image, it should continue booting on our Linux-Clients.
## Steps to reproduce the behaviour
PXE-Configuration for atftpd: [gitlab](https://git.informatik.fh-nuernberg.de/Linux-Infrastruktur-Automatisierung/Konfigurationsmanagement/tree/master/PXE)
OBS-Repository: see above
## OS and Software information
+ KIWI version: openSUSE OBS
+ Operating system: openSUSE Leap 15.0
+ OBS version: openSUSE OBS

**Comment by schaefi** [comment]
Looks like ip reports no interfaces, which usually points to no drivers available for the network card(s) in your machine. I'm not aware how you built the image but I think you should check if the netboot initrd you are propagating with pxe contains all drivers to support your hardware

**Comment by schaefi** [comment]
unrelated to the issue here; If you plan on a new project with pxe deployment I strongly recommend to switch step away from the kiwi custom netboot code and use the new concept with disk based deployment and dracut featured initrd. For details see: 

* https://opensource.suse.com/kiwi/building/build_oem_disk.html#deploy-from-network

**Comment by skriesch** [comment]
Drivers are part of the kernel. openSUSE Leap 15.0 can be installed without any problem from DVD or with added repo via HTTP in the PXE configuration. Where should we add special drivers for the network card then? We are using a Leap kernel.

**Comment by schaefi** [comment]
> Drivers are part of the kernel

what counts is if they are part of the initrd such that the kernel can load them. You can boot from the dvd; That's nice but unrelated to booting from the network if I understand your use case correctly

I checked out your project: home:Maini12:branches:home:AdaLovelace:linuxlaboratory/openSUSE-Leap-15.0 and unpacked the result:

* opensuse-leap-15.0-image.x86_64-2.8.0-Build61.1.tar.xz

part of the results is the initrd which you use on your pxe server to boot the client. I checked the contents:

```
xz -cd opensuse-leap-15.0-image.x86_64-2.8.0.initrd.xz | cpio -it | grep modules | grep kernel/drivers/net/ethernet
```

* That looks pretty good and complete. Can you confirm that one of these drivers supports your network card ?

If that makes sense to you and your pxe server really uses that initrd at boot time we should go and find why the client has no interfaces. Therefore please boot the client with the following boot option:

* kiwidebug=1

This will lead to a shell instead of the rebootException. If you are in that shell check if the kernel is the expected one, if you can find the drivers, check dmesg... and so on.

**Comment by schaefi** [comment]
Please also check if the kernel version matches the initrd. You can do that with

```
uname -a
```

and compare /lib/modules/ to be compatible with the loaded kernel. I often seen pxe server setup where kernel and initrd are not matching. This leads to the situation that no kernel modules can be loaded

**Comment by skriesch** [comment]
Thank you for this fast support! That was really helpfully.
I have added the default kernel from the Leap repo (testing via HTTP) and the kernel of our own image for debugging.

**Comment by schaefi** [comment]
You are welcome

Ah ok, so it was a kernel mismatch. I stumbled over that type of problem too in the past ;)
