### ISSUE TITLE
Better changelog handling

### ISSUE THREAD

**Issue by schaefi** [SUSE/kiwi#979]
## Problem description

The changelog for the package build is created via a script ```helper/changelog_generator```
The script takes the entire git history into account and writes the changelog file. This approach
however has some disadvantages:

* A change in the format of e.g the author of a contributor would cause a change of
  entries from the past too.

* The fix for a bug in the script would cause entries from the past to be fixed too

The problem with changing entries from the past is that at least for suse the validation
and checker tools consider this evil and will decline the package submission

## Solution Idea

The idea is now to keep a base changelog file inside the kiwi git and only update that
file with new changelog entries that appears from the git history. This concept would allow
us to keep an base file even with "errors" but don't violate checkers from the distribution.

Thoughts ?

**Comment by dcermak** [comment]
There is a tool for this workflow: [tito](https://github.com/dgoodwin/tito).

I have unfortunately never used tito extensively and only tried it a few years ago, so the information below might not be 100% accurate:
tito creates a changelog by extracting the git log from between two tags and pushes it at the top of the `%changelog` section of the spec file (by default tito will only create a changelog entry in between tags). This is however only a small portion of what tito can do: it can also build source rpms from the repository, build actual rpms via mock and kick of builds on Fedora's COPR and Koji.

This also outlines a potential problem with tito: it is very Fedora specific. SUSE does not use the `%changelog` section, so this would have to be extracted on each spec update (afaik there is an obs script for that). On top of that, tito really shines for packages where the whole git repository is packed into a tarball, the tarball put into a source rpm and rpmbuild takes care of building everything. This is however not the case for KIWI: the documentation is not build by rpmbuild, but created beforehand and put into the source rpm.

So I see two options:
1. Use tito and refactor the rpm creation process so that we can just tar the whole repo and rpmbuild takes care of the rest.
or
2. Create a custom python/perl/ruby/$your_favorite_scripting_language_here script that will just prepend changelog entries to the kiwi.changes file.

**Comment by Conan-Kudo** [comment]
@schaefi At least in my experience with submitting things to openSUSE, fixing entries of the past will cause auto-decline. If that's the case for SUSE internally, that's probably broken, since there are good reasons to fix entries from the past.

@dcermak While upstream hasn't tagged a release with it yet, I had taken some of the patches from the SUSE Manager team and fixed them up to upstream support for SUSE-style detached changelogs some time ago: https://github.com/dgoodwin/tito/commit/9494cc13b7c4d6fdf1050abfbf2a9400c2ff2beb

It does support releasing to OBS, it's just not functionality used much in the RH/Fedora ecosystem. But it definitely works because Uyuni and SUSE Manager release this way.

**Comment by dcermak** [comment]
> @dcermak While upstream hasn't tagged a release with it yet, I had taken some of the patches from the SUSE Manager team and fixed them up to upstream support for SUSE-style detached changelogs some time ago: dgoodwin/tito@9494cc1

That's neat! Then we could probably use tito, unfortunately it is not packaged for openSUSE though.

**Comment by Conan-Kudo** [comment]
> At least in my experience with submitting things to openSUSE, fixing entries of the past will cause auto-decline.
@schaefi I meant _not_ cause auto-decline. :)

**Comment by schaefi** [comment]
> There is a tool for this workflow: tito.

Thanks for sharing, this is an interesting project. tito does a lot more than managing the changelog. It could basically replace all the self written scripts and the build: target of the Makefile. We can keep this information as a refactoring task for the future.

> Build packages off an "upstream" git repository, where modifications in the "downstream" git repository will be applied as a patch in the source rpm.

wow.

pretty powerful tool

For the sake of getting started with the changelog issue I think my open PR #997 is a good start, but tito sounds nice. If we consider it in the future we need a package. Interesting it's written in python but could not find it on the pip search index

**Comment by dcermak** [comment]
Shouldn't we keep it this open as a reminder for tito?

**Comment by Conan-Kudo** [comment]
@dcermak I'd suggest making a new issue specifically about considering to use tito.
